#pragma once
// Web API route constants, generated by including api_routes.def (the
// single source of truth - see the header comment there). All route
// registration and any in-code reference to an /api path goes through
// these constants; tools/check_api_parity.py fails the build on raw
// /api string literals anywhere else.
namespace Web {
namespace ApiRoutes {
#define ROUTE(name, methods, path)     constexpr const char* name = path;
#define ROUTE_OPT(name, methods, path) constexpr const char* name = path;
#include "api_routes.def"
#undef ROUTE
#undef ROUTE_OPT
}  // namespace ApiRoutes
}  // namespace Web
