#!/usr/bin/env python3
"""Generate src/Sensors/LandMask.h: a compact equirectangular land/sea
bitmap from Natural Earth 110m coastlines (npm world-atlas land-110m,
TopoJSON). Rasterizes continent polygons into a 180x90 1bpp mask. The
GPS globe screen samples it by lat/lon. Run from the repo root with
the .venv python; needs land-110m.json alongside (fetch from
https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json)."""
import json, sys
from PIL import Image, ImageDraw

src = sys.argv[1] if len(sys.argv) > 1 else "land-110m.json"
topo = json.load(open(src))
tr = topo["transform"]; sx, sy = tr["scale"]; tx, ty = tr["translate"]
arcs_raw = topo["arcs"]
def decode(a):
    pts = []; x = y = 0
    for dx, dy in a:
        x += dx; y += dy; pts.append((x*sx+tx, y*sy+ty))
    return pts
arcs = [decode(a) for a in arcs_raw]
def ring(idxs):
    pts = []
    for i in idxs:
        a = arcs[i] if i >= 0 else list(reversed(arcs[~i]))
        if pts and a and pts[-1] == a[0]: pts.extend(a[1:])
        else: pts.extend(a)
    return pts
MW, MH = 180, 90
img = Image.new("1", (MW, MH), 0); dr = ImageDraw.Draw(img)
def ll(lo, la): return ((lo+180)/360*MW, (90-la)/180*MH)
for g in topo["objects"]["land"]["geometries"]:
    polys = g["arcs"] if g["type"] == "MultiPolygon" else [g["arcs"]]
    for poly in polys:
        xy = [ll(lo, la) for lo, la in ring(poly[0])]
        if len(xy) >= 3: dr.polygon(xy, fill=1)
px = img.load(); stride = (MW+7)//8; packed = bytearray()
for y in range(MH):
    for bx in range(stride):
        b = 0
        for bit in range(8):
            x = bx*8+bit
            if x < MW and px[x, y]: b |= 0x80 >> bit
        packed.append(b)
with open("src/Sensors/LandMask.h", "w") as f:
    f.write("// Natural Earth 110m land mask, equirectangular, 1 bit per cell\n")
    f.write("// (lon -180..180 across, lat 90..-90 down; bit set = land).\n")
    f.write("// Generated by tools/gen_landmask.py from world-atlas land-110m;\n")
    f.write("// regenerate, do not hand-edit. ~%d bytes.\n#pragma once\n\n" % len(packed))
    f.write("#include <stdint.h>\n#include <pgmspace.h>\n\n")
    f.write("namespace Sensors {\nnamespace LandMask {\n\n")
    f.write("inline constexpr int W = %d;\ninline constexpr int H = %d;\ninline constexpr int STRIDE = %d;\n\n" % (MW, MH, stride))
    f.write("inline const uint8_t DATA[] PROGMEM = {\n")
    for i in range(0, len(packed), 20):
        f.write("  " + ",".join("0x%02X" % b for b in packed[i:i+20]) + ",\n")
    f.write("};\n\n")
    f.write("inline bool is_land(int lat_d, int lon_d) {\n")
    f.write("  lon_d = ((lon_d + 180) % 360 + 360) % 360 - 180;\n")
    f.write("  int mx = (int)((lon_d + 180) / 360.0f * W); if (mx < 0) mx = 0; if (mx >= W) mx = W - 1;\n")
    f.write("  int my = (int)((90 - lat_d) / 180.0f * H); if (my < 0) my = 0; if (my >= H) my = H - 1;\n")
    f.write("  const uint8_t byte = pgm_read_byte(&DATA[my * STRIDE + (mx >> 3)]);\n")
    f.write("  return (byte >> (7 - (mx & 7))) & 1;\n}\n\n")
    f.write("}  // namespace LandMask\n}  // namespace Sensors\n")
print("wrote src/Sensors/LandMask.h (%d bytes)" % len(packed))
