#pragma once

// WebUI — HTTP/SSE bridge between browser SPAs and the LXMF gateway.
//
// Registers routes on the existing WebServer (declared in Console.h) so the
// same port-80 instance serves both the legacy console docs and our /api/*
// surface. The server is brought up by WebUI::start() once WiFi is up,
// independent of the legacy console-mode path. Both code paths share a
// `_started` guard so server.begin() is only called once.

#include <Arduino.h>
#include <WebServer.h>
#include <uri/UriBraces.h>
#include <ArduinoJson.h>
#include <Log.h>
#include <Transport.h>

#include "../LXMF/LXMFGateway.h"
#include "../LXMF/LXMFTypes.h"
#include "AuthTokens.h"
#include "SPAEmbedded.h"

// EEPROM helpers + WiFi config constants from the existing firmware.
// Used by the bootstrap-mode WiFi configure endpoint.
#include "../Config.h"   // WR_WIFI_OFF/STA/AP, config_addr()
#include "../ROM.h"      // ADDR_CONF_SSID, ADDR_CONF_PSK
extern void eeprom_update(int mapped_addr, uint8_t byte);
extern void wr_conf_save(uint8_t mode);
extern bool eeprom_have_conf();
extern uint32_t lora_freq;
extern uint32_t lora_bw;
extern int      lora_sf;
extern int      lora_cr;
extern int      lora_txp;
extern bool     radio_online;

#include <vector>
#include <string>

extern WebServer server;          // declared in Console.h
extern bool      wifi_initialized;
extern microStore::FileSystem filesystem;

namespace Web {

  // Single-use 6-hex-char identity code generated by a button press on
  // the device. Required for /api/accounts (create), /api/auth/login,
  // /api/wifi/configure, /api/radio. Proves physical possession of the
  // device — same role as PSK-on-back-of-router but ephemeral.
  // Lives only in RAM; expires after IDENTITY_CODE_TTL_MS.
  struct IdentityCode {
    std::string  hex6;        // first 6 chars of a 16-byte random token
    uint32_t     expires_ms;  // millis() snapshot
    bool         consumed;
  };

  class WebUI {
  public:
    static constexpr uint32_t IDENTITY_CODE_TTL_MS = 60UL * 1000UL;

    // Set by the firmware setup() path when WiFi failed to come up in STA
    // mode and we fell back to softAP. Toggles /api/wifi/* into the
    // unauthenticated bootstrap configuration mode.
    static inline bool bootstrap_mode = false;

    // Called once at boot, after WiFi STA is up. Idempotent.
    static void start() {
      if (_started) return;
      _started = true;
      AuthTokens::load();
      register_routes();
      static const char* collect[] = {"Authorization"};
      server.collectHeaders(collect, sizeof(collect)/sizeof(collect[0]));
      server.begin();
      NOTICE("WebUI: listening on port 80");
    }

    // Main-loop hook. Drives request handling and token expiry sweep.
    static void loop() {
      if (!_started) return;
      server.handleClient();
      uint32_t now = millis();
      if (now - _last_sweep > 60000) {
        _last_sweep = now;
        AuthTokens::sweep_expired();
        if (id_code().expires_ms != 0 && now > id_code().expires_ms) {
          id_code().hex6.clear();
          id_code().expires_ms = 0;
          id_code().consumed = false;
        }
      }
    }

    // Called from the button handler in RNode_Firmware.ino when the user
    // short-presses the device's USR1 button. Generates a fresh 16-byte
    // random; the first 6 hex chars are the proof we'll demand on the next
    // auth-sensitive request. The full hex is printed to serial so the
    // operator can see it (OLED integration is a later step).
    static void on_button_request_identity_code() {
      RNS::Bytes b = RNS::Cryptography::random(16);
      std::string hex = b.toHex();
      id_code().hex6      = hex.substr(0, 6);
      id_code().expires_ms = millis() + IDENTITY_CODE_TTL_MS;
      id_code().consumed  = false;
      // Visible to the operator. Also fires an SSE notification so any
      // logged-in browser can prompt the user to enter the code.
      NOTICEF("WebUI: identity code = %s (60s) — type the first 6 chars into the browser",
              hex.c_str());
      Serial.print("\n\n==== IDENTITY CODE: ");
      Serial.print(id_code().hex6.c_str());
      Serial.println(" (valid 60s) ====\n");
      _id_code_event_pending = true;
    }

    // Display accessors so the OLED renderer can show the identity code
    // without coupling Display.h to the rest of the WebUI internals. Read
    // each frame; returns empty / 0 if no identity code is pending.
    static const std::string& identity_code_for_display() {
      static const std::string empty;
      auto& u = id_code();
      if (u.hex6.empty() || u.consumed) return empty;
      if (millis() > u.expires_ms) return empty;
      return u.hex6;
    }

    static uint32_t identity_code_remaining_ms() {
      auto& u = id_code();
      if (u.hex6.empty() || u.consumed) return 0;
      uint32_t now = millis();
      if (now > u.expires_ms) return 0;
      return u.expires_ms - now;
    }

    // Check that the given proof is currently valid. Single-use: marks the
    // unlock as consumed on success.
    static bool consume_identity_code(const std::string& proof) {
      if (proof.empty() || id_code().hex6.empty() || id_code().consumed) return false;
      if (millis() > id_code().expires_ms) return false;
      // Constant-time-ish comparison.
      if (proof.size() != id_code().hex6.size()) return false;
      uint8_t diff = 0;
      for (size_t i = 0; i < proof.size(); i++) diff |= proof[i] ^ id_code().hex6[i];
      if (diff != 0) return false;
      id_code().consumed = true;
      return true;
    }

  private:
    // ---- Helpers ----

    static IdentityCode& id_code() {
      static IdentityCode u{"", 0, false};
      return u;
    }

    static void send_json(int code, const JsonDocument& doc) {
      String body;
      serializeJson(doc, body);
      server.send(code, "application/json", body);
    }

    static void send_error(int code, const char* msg) {
      JsonDocument doc;
      doc["error"]   = msg;
      send_json(code, doc);
    }

    // Extract bearer-token account from the Authorization header. Falls
    // back to a `token` query-string param so EventSource (which can't set
    // headers) can authenticate. Sends 401 and returns empty on failure.
    static LXMF::AccountId require_auth() {
      std::string token;
      String h = server.header("Authorization");
      if (h.startsWith("Bearer ")) {
        String hex_str = h.substring(7);
        hex_str.trim();
        token = std::string(hex_str.c_str());
      } else if (server.hasArg("token")) {
        token = std::string(server.arg("token").c_str());
      } else {
        send_error(401, "missing_bearer");
        return {};
      }
      LXMF::AccountId acc = AuthTokens::validate(token);
      if (acc.empty()) {
        send_error(401, "invalid_or_expired_token");
      }
      return acc;
    }

    // Read JSON body. Returns empty doc on failure (and sends a 400 to the
    // client).
    static bool read_body_json(JsonDocument& out) {
      String body = server.arg("plain");
      DeserializationError err = deserializeJson(out, body);
      if (err) {
        send_error(400, "invalid_json");
        return false;
      }
      return true;
    }

    static RNS::Bytes hex_to_bytes(const std::string& hex, size_t expected = 0) {
      RNS::Bytes b;
      if (hex.empty()) return b;
      if (expected > 0 && hex.size() != expected * 2) return b;
      b.assignHex(hex.c_str());
      return b;
    }

    // ---- Routes ----

    static void register_routes() {
      // SPA — single embedded HTML file, served gzipped at / and /index.html
      server.on("/",            HTTP_GET, handle_spa);
      server.on("/index.html",  HTTP_GET, handle_spa);
      // Public
      server.on("/api/info",          HTTP_GET,  handle_info);
      // Auth
      server.on("/api/auth/login",    HTTP_POST, handle_login);
      server.on("/api/auth/logout",   HTTP_POST, handle_logout);
      // Accounts
      server.on("/api/accounts",      HTTP_POST, handle_create_account);
      server.on(UriBraces("/api/accounts/{}"), HTTP_GET, handle_get_account);
      server.on(UriBraces("/api/accounts/{}/announce"), HTTP_POST, handle_announce);
      server.on(UriBraces("/api/accounts/{}/inbox"),    HTTP_GET,  handle_inbox);
      server.on(UriBraces("/api/accounts/{}/outbox"),   HTTP_GET,  handle_outbox);
      server.on(UriBraces("/api/accounts/{}/send"),     HTTP_POST, handle_send);
      server.on(UriBraces("/api/accounts/{}/events"),   HTTP_GET,  handle_events);
      // Paths
      server.on("/api/paths",         HTTP_GET,  handle_paths_list);
      server.on("/api/paths/lookup",  HTTP_POST, handle_path_lookup);
      // WiFi config — gated by bearer token OR identity_code in body.
      // Reboots on save.
      server.on("/api/wifi/scan",     HTTP_GET,  handle_wifi_scan);
      server.on("/api/wifi/configure",HTTP_POST, handle_wifi_configure);
      // Radio config — read requires bearer auth; write/reset require
      // bearer OR identity_code. Both write paths reboot on success.
      server.on("/api/radio",         HTTP_GET,  handle_radio_get);
      server.on("/api/radio",         HTTP_POST, handle_radio_set);
      server.on("/api/radio/reset",   HTTP_POST, handle_radio_reset);
    }

    static void handle_spa() {
      server.sendHeader("Content-Encoding", "gzip");
      server.sendHeader("Cache-Control", "no-cache");
      server.send_P(200, "text/html",
                    reinterpret_cast<const char*>(Web::SPA_HTML_GZ),
                    Web::SPA_HTML_GZ_LEN);
    }

    static void handle_info() {
      JsonDocument doc;
      doc["fw_version"] = "lxmf-gateway-0.1";
      doc["uptime_ms"]  = (uint32_t)millis();
      doc["bootstrap"]  = bootstrap_mode;
      doc["identity_code_pending"] = !id_code().hex6.empty() && !id_code().consumed
                              && millis() < id_code().expires_ms;
      JsonArray accts = doc["accounts"].to<JsonArray>();
      for (const auto* a : LXMF::LXMFGateway::active_accounts()) {
        JsonObject obj = accts.add<JsonObject>();
        obj["id"]           = a->id;
        obj["display_name"] = a->display_name;
        obj["address"]      = a->address_hex();
      }
      send_json(200, doc);
    }

    static void handle_login() {
      JsonDocument body;
      if (!read_body_json(body)) return;
      const char* acc_str   = body["account_id"]   | "";
      const char* proof_str = body["identity_code"] | "";
      if (!*acc_str) { send_error(400, "missing_account_id"); return; }
      LXMF::AccountId acc_id = acc_str;
      if (!LXMF::LXMFGateway::account_by_id(acc_id)) {
        send_error(404, "unknown_account");
        return;
      }
      if (!consume_identity_code(proof_str)) {
        send_error(401, "identity_code_required");
        return;
      }
      std::string token = AuthTokens::issue(acc_id);
      if (token.empty()) {
        send_error(500, "token_issue_failed");
        return;
      }
      JsonDocument doc;
      doc["token"]         = token;
      doc["account_id"]    = acc_id;
      doc["expires_in_s"]  = AuthTokens::DEFAULT_TTL_S;
      send_json(200, doc);
    }

    static void handle_logout() {
      String h = server.header("Authorization");
      if (h.startsWith("Bearer ")) {
        String hex_str = h.substring(7);
        hex_str.trim();
        AuthTokens::revoke(std::string(hex_str.c_str()));
      }
      server.send(204, "text/plain", "");
    }

    static void handle_create_account() {
      JsonDocument body;
      if (!read_body_json(body)) return;
      const char* name      = body["display_name"] | "";
      const char* proof_str = body["identity_code"] | "";
      if (!*name) { send_error(400, "missing_display_name"); return; }
      if (!consume_identity_code(proof_str)) {
        send_error(401, "identity_code_required");
        return;
      }
      LXMF::AccountId acc_id = LXMF::LXMFGateway::create_account(name);
      if (acc_id.empty()) {
        send_error(500, "create_failed");
        return;
      }
      std::string token = AuthTokens::issue(acc_id);
      const LXMF::LXMFAccount* a = LXMF::LXMFGateway::account_by_id(acc_id);
      JsonDocument doc;
      doc["id"]      = acc_id;
      doc["address"] = a ? a->address_hex() : "";
      doc["token"]   = token;
      send_json(200, doc);
    }

    static void handle_get_account() {
      LXMF::AccountId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      const LXMF::LXMFAccount* a = LXMF::LXMFGateway::account_by_id(requested);
      if (!a) { send_error(404, "unknown_account"); return; }
      JsonDocument doc;
      doc["id"]                   = a->id;
      doc["display_name"]         = a->display_name;
      doc["address"]              = a->address_hex();
      doc["announce_interval_ms"] = a->announce_interval_ms;
      doc["inbox_size"]           = a->inbox  ? (uint32_t)a->inbox->size()  : 0;
      doc["outbox_size"]          = a->outbox ? (uint32_t)a->outbox->size() : 0;
      send_json(200, doc);
    }

    static void handle_announce() {
      LXMF::AccountId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      if (!LXMF::LXMFGateway::announce(requested)) {
        send_error(404, "unknown_account");
        return;
      }
      JsonDocument doc;
      doc["status"] = "announced";
      send_json(200, doc);
    }

    static void emit_messages_array(JsonArray arr,
                                    const std::vector<LXMF::MessageRecord>& msgs) {
      for (const auto& m : msgs) {
        JsonObject obj = arr.add<JsonObject>();
        obj["seq"]     = m.seq;
        obj["ts"]      = m.ts;
        obj["peer"]    = m.peer_hash.toHex();
        obj["title"]   = m.title;
        obj["body"]    = m.content;
        obj["sig_ok"]  = m.signature_ok;
        obj["status"]  = LXMF::outbox_status_name(m.status);
      }
    }

    static void handle_inbox() {
      LXMF::AccountId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      const LXMF::LXMFAccount* a = LXMF::LXMFGateway::account_by_id(requested);
      if (!a || !a->inbox) { send_error(404, "unknown_account"); return; }
      uint32_t since = (uint32_t)server.arg("since").toInt();
      size_t   limit = (size_t)server.arg("limit").toInt();
      if (limit == 0 || limit > 50) limit = 50;
      auto msgs = since > 0 ? a->inbox->since(since) : a->inbox->recent(limit);
      JsonDocument doc;
      JsonArray arr = doc["messages"].to<JsonArray>();
      emit_messages_array(arr, msgs);
      doc["next_since"] = a->inbox->next_seq();
      send_json(200, doc);
    }

    static void handle_outbox() {
      LXMF::AccountId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      const LXMF::LXMFAccount* a = LXMF::LXMFGateway::account_by_id(requested);
      if (!a || !a->outbox) { send_error(404, "unknown_account"); return; }
      uint32_t since = (uint32_t)server.arg("since").toInt();
      size_t   limit = (size_t)server.arg("limit").toInt();
      if (limit == 0 || limit > 50) limit = 50;
      auto msgs = since > 0 ? a->outbox->since(since) : a->outbox->recent(limit);
      JsonDocument doc;
      JsonArray arr = doc["messages"].to<JsonArray>();
      emit_messages_array(arr, msgs);
      doc["next_since"] = a->outbox->next_seq();
      send_json(200, doc);
    }

    static void handle_send() {
      LXMF::AccountId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      JsonDocument body;
      if (!read_body_json(body)) return;
      std::string to_hex  = (const char*)(body["to"]     | "");
      std::string title   = (const char*)(body["title"]  | "");
      std::string content = (const char*)(body["body"]   | "");
      if (content.empty()) { send_error(400, "missing_body"); return; }
      RNS::Bytes to = hex_to_bytes(to_hex, LXMF::HASH_LEN);
      if (to.size() != LXMF::HASH_LEN) {
        send_error(400, "invalid_destination_hash");
        return;
      }
      LXMF::MessageRecord rec;
      if (!LXMF::LXMFGateway::send(requested, to, title, content, rec)) {
        send_error(503, "send_failed");
        return;
      }
      JsonDocument doc;
      doc["queued_seq"] = rec.seq;
      doc["status"]     = LXMF::outbox_status_name(rec.status);
      send_json(202, doc);
    }

    static void handle_events() {
      // Short-poll dressed as SSE: drain any events newer than `since`,
      // send a retry: hint so the browser reconnects quickly, and return.
      // This keeps the main Arduino task free to service the LoRa modem
      // and reticulum.loop() — parking the handler for any meaningful
      // duration would block both, since handleClient() runs synchronously
      // inside the same loop iteration.
      LXMF::AccountId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      const LXMF::LXMFAccount* a = LXMF::LXMFGateway::account_by_id(requested);
      if (!a || !a->inbox) { send_error(404, "unknown_account"); return; }

      uint32_t since = (uint32_t)server.arg("since").toInt();

      server.sendHeader("Cache-Control", "no-cache");
      server.sendHeader("Connection", "close");
      server.setContentLength(CONTENT_LENGTH_UNKNOWN);
      server.send(200, "text/event-stream", "");
      // Tell EventSource to reconnect every 500 ms instead of the 3 s
      // browser default. Combined with the immediate return below this
      // gives sub-second event-delivery latency without busy-parking.
      server.sendContent("retry: 500\n\n");

      auto pending = a->inbox->since(since);
      for (const auto& m : pending) {
        JsonDocument item;
        item["type"] = "incoming";
        JsonObject msg = item["msg"].to<JsonObject>();
        msg["seq"]    = m.seq;
        msg["ts"]     = m.ts;
        msg["peer"]   = m.peer_hash.toHex();
        msg["title"]  = m.title;
        msg["body"]   = m.content;
        msg["sig_ok"] = m.signature_ok;
        String line;
        serializeJson(item, line);
        server.sendContent(String("data: ") + line + "\n\n");
      }
      if (_id_code_event_pending) {
        _id_code_event_pending = false;
        server.sendContent("data: {\"type\":\"identity_code_available\"}\n\n");
      }
      // Connection closes when the handler returns; browser reconnects
      // after `retry:` ms with an updated `since` query param.
    }

    // Verify that this request has physical-presence authority — either a
    // valid bearer token (which required a button press to obtain) or a
    // current identity_code in the request body.
    static bool require_physical_auth(const JsonDocument& body) {
      String h = server.header("Authorization");
      if (h.startsWith("Bearer ")) {
        String hex_str = h.substring(7); hex_str.trim();
        LXMF::AccountId acc = AuthTokens::validate(std::string(hex_str.c_str()));
        if (!acc.empty()) return true;
      }
      const char* code = body["identity_code"] | "";
      if (consume_identity_code(code)) return true;
      send_error(401, "identity_code_required");
      return false;
    }

    static void handle_wifi_scan() {
      // Scan results aren't sensitive; gate only the configure write.
      int n = WiFi.scanNetworks();
      JsonDocument doc;
      JsonArray arr = doc["networks"].to<JsonArray>();
      for (int i = 0; i < n; i++) {
        JsonObject obj = arr.add<JsonObject>();
        obj["ssid"]    = WiFi.SSID(i);
        obj["rssi"]    = WiFi.RSSI(i);
        obj["secure"]  = WiFi.encryptionType(i) != WIFI_AUTH_OPEN;
      }
      WiFi.scanDelete();
      send_json(200, doc);
    }

    static void handle_wifi_configure() {
      JsonDocument body;
      if (!read_body_json(body)) return;
      if (!require_physical_auth(body)) return;
      String ssid = body["ssid"] | "";
      String psk  = body["psk"]  | "";
      if (ssid.length() == 0 || ssid.length() > 32) {
        send_error(400, "invalid_ssid");
        return;
      }
      if (psk.length() > 32) {
        send_error(400, "invalid_psk");
        return;
      }
      // Write SSID, PSK, and STA mode to EEPROM using the same code paths
      // as CMD_WIFI_SSID / CMD_WIFI_PSK / CMD_WIFI_MODE in serial_callback.
      for (uint8_t i = 0; i < 33; i++) {
        uint8_t c = (i < ssid.length() && i < 32) ? (uint8_t)ssid[i] : 0x00;
        eeprom_update(config_addr(ADDR_CONF_SSID + i), c);
      }
      for (uint8_t i = 0; i < 33; i++) {
        uint8_t c = (i < psk.length() && i < 32) ? (uint8_t)psk[i] : 0x00;
        eeprom_update(config_addr(ADDR_CONF_PSK + i), c);
      }
      wr_conf_save(WR_WIFI_STA);

      JsonDocument doc;
      doc["status"]  = "saved";
      doc["restart"] = true;
      send_json(200, doc);

      // Reboot so STA mode applies cleanly.
      delay(500);
      ESP.restart();
    }

    static void handle_radio_get() {
      if (require_auth().empty()) return;
      JsonDocument doc;
      doc["freq_hz"] = (uint32_t)lora_freq;
      doc["bw_hz"]   = (uint32_t)lora_bw;
      doc["sf"]      = lora_sf;
      doc["cr"]      = lora_cr;
      doc["txp"]     = lora_txp;
      doc["have_conf"] = eeprom_have_conf();
      doc["radio_online"] = radio_online;
      doc["op_mode"] = (op_mode == MODE_TNC) ? "tnc" : "host";
      // Soft limits — actual modem-side validation happens on the next boot.
      doc["limits"]["sf_min"] = 5;
      doc["limits"]["sf_max"] = 12;
      doc["limits"]["cr_min"] = 5;
      doc["limits"]["cr_max"] = 8;
      doc["limits"]["txp_max"] = 22;
      send_json(200, doc);
    }

    static void handle_radio_set() {
      JsonDocument body;
      if (!read_body_json(body)) return;
      if (!require_physical_auth(body)) return;
      uint32_t freq = (uint32_t)(body["freq_hz"] | 0);
      uint32_t bw   = (uint32_t)(body["bw_hz"]   | 0);
      int      sf   = (int)(body["sf"]    | -1);
      int      cr   = (int)(body["cr"]    | -1);
      int      txp  = (int)(body["txp"]   | -1);
      if (freq == 0 || bw == 0 || sf < 5 || sf > 12 || cr < 5 || cr > 8 ||
          txp < 0 || txp > 22) {
        send_error(400, "invalid_radio_params");
        return;
      }
      // Direct EEPROM write, mirroring eeprom_conf_save() but bypassing
      // its hw_ready+radio_online guard. On a fresh device the radio is
      // offline because no saved config exists, which is the very state
      // this endpoint is meant to resolve. Address layout matches
      // ROM.h ADDR_CONF_{SF,CR,TXP,BW,FREQ,OK}.
      eeprom_update(eeprom_addr(ADDR_CONF_SF),  (uint8_t)sf);
      eeprom_update(eeprom_addr(ADDR_CONF_CR),  (uint8_t)cr);
      eeprom_update(eeprom_addr(ADDR_CONF_TXP), (uint8_t)txp);
      eeprom_update(eeprom_addr(ADDR_CONF_BW)+0,  (uint8_t)(bw >> 24));
      eeprom_update(eeprom_addr(ADDR_CONF_BW)+1,  (uint8_t)(bw >> 16));
      eeprom_update(eeprom_addr(ADDR_CONF_BW)+2,  (uint8_t)(bw >> 8));
      eeprom_update(eeprom_addr(ADDR_CONF_BW)+3,  (uint8_t)bw);
      eeprom_update(eeprom_addr(ADDR_CONF_FREQ)+0, (uint8_t)(freq >> 24));
      eeprom_update(eeprom_addr(ADDR_CONF_FREQ)+1, (uint8_t)(freq >> 16));
      eeprom_update(eeprom_addr(ADDR_CONF_FREQ)+2, (uint8_t)(freq >> 8));
      eeprom_update(eeprom_addr(ADDR_CONF_FREQ)+3, (uint8_t)freq);
      eeprom_update(eeprom_addr(ADDR_CONF_OK), CONF_OK_BYTE);

      JsonDocument doc;
      doc["status"]  = "saved";
      doc["restart"] = true;
      send_json(200, doc);
      delay(500);
      ESP.restart();
    }

    static void handle_radio_reset() {
      JsonDocument body;
      if (!read_body_json(body)) return;
      if (!require_physical_auth(body)) return;
      eeprom_update(eeprom_addr(ADDR_CONF_OK), 0x00);
      JsonDocument doc;
      doc["status"]  = "cleared";
      doc["restart"] = true;
      send_json(200, doc);
      delay(500);
      ESP.restart();
    }

    static void handle_paths_list() {
      if (require_auth().empty()) return;
      // Dump everything in Transport::_path_table. Each entry is one
      // destination the device has learned about via an announce, along
      // with hop count and the timestamp of the announce.
      const auto& tbl = RNS::Transport::get_path_table();
      JsonDocument doc;
      JsonArray arr = doc["paths"].to<JsonArray>();
      for (const auto& kv : tbl) {
        JsonObject obj = arr.add<JsonObject>();
        obj["dest"]  = kv.first.toHex();
        obj["hops"]  = (int)kv.second._hops;
        obj["ts"]    = kv.second._timestamp;
        obj["from"]  = kv.second._received_from.toHex();
      }
      doc["count"] = (uint32_t)tbl.size();
      send_json(200, doc);
    }

    static void handle_path_lookup() {
      LXMF::AccountId caller = require_auth();
      if (caller.empty()) return;
      JsonDocument body;
      if (!read_body_json(body)) return;
      std::string to_hex = (const char*)(body["to"] | "");
      RNS::Bytes to = hex_to_bytes(to_hex, LXMF::HASH_LEN);
      if (to.size() != LXMF::HASH_LEN) {
        send_error(400, "invalid_destination_hash");
        return;
      }
      bool known = RNS::Transport::has_path(to);
      JsonDocument doc;
      doc["known"] = known;
      if (!known) {
        RNS::Transport::request_path(to);
        doc["requested"] = true;
      }
      send_json(200, doc);
    }

  private:
    static inline bool     _started = false;
    static inline uint32_t _last_sweep = 0;
    static inline bool     _id_code_event_pending = false;
  };

}
