#pragma once

// WebUI — HTTP/SSE bridge between browser SPAs and the LXMF gateway.
//
// Registers routes on the existing WebServer (declared in Console.h) so the
// same port-80 instance serves both the legacy console docs and our /api/*
// surface. The server is brought up by WebUI::start() once WiFi is up,
// independent of the legacy console-mode path. Both code paths share a
// `_started` guard so server.begin() is only called once.

#include <Arduino.h>
#include <WebServer.h>
#include <uri/UriBraces.h>
#include <ArduinoJson.h>
#include <Log.h>
#include <Transport.h>

#include "../LXMF/LXMFGateway.h"
#include "../LXMF/LXMFTypes.h"
#include "AuthTokens.h"

#include <vector>
#include <string>

extern WebServer server;          // declared in Console.h
extern bool      wifi_initialized;
extern microStore::FileSystem filesystem;

namespace Web {

  // Single-use 6-hex-char unlock proof generated by a button press on the
  // device. Required for /api/accounts (create) and /api/auth/login.
  // Lives only in RAM; expires after UNLOCK_TTL_MS.
  struct UnlockProof {
    std::string  hex6;        // first 6 chars of a 16-byte random token
    uint32_t     expires_ms;  // millis() snapshot
    bool         consumed;
  };

  class WebUI {
  public:
    static constexpr uint32_t UNLOCK_TTL_MS = 60UL * 1000UL;

    // Called once at boot, after WiFi STA is up. Idempotent.
    static void start() {
      if (_started) return;
      _started = true;
      AuthTokens::load();
      register_routes();
      static const char* collect[] = {"Authorization"};
      server.collectHeaders(collect, sizeof(collect)/sizeof(collect[0]));
      server.begin();
      NOTICE("WebUI: listening on port 80");
    }

    // Main-loop hook. Drives request handling and token expiry sweep.
    static void loop() {
      if (!_started) return;
      server.handleClient();
      uint32_t now = millis();
      if (now - _last_sweep > 60000) {
        _last_sweep = now;
        AuthTokens::sweep_expired();
        if (unlock().expires_ms != 0 && now > unlock().expires_ms) {
          unlock().hex6.clear();
          unlock().expires_ms = 0;
          unlock().consumed = false;
        }
      }
    }

    // Called from the button handler in RNode_Firmware.ino when the user
    // short-presses the device's USR1 button. Generates a fresh 16-byte
    // random; the first 6 hex chars are the proof we'll demand on the next
    // auth-sensitive request. The full hex is printed to serial so the
    // operator can see it (OLED integration is a later step).
    static void on_button_unlock() {
      RNS::Bytes b = RNS::Cryptography::random(16);
      std::string hex = b.toHex();
      unlock().hex6      = hex.substr(0, 6);
      unlock().expires_ms = millis() + UNLOCK_TTL_MS;
      unlock().consumed  = false;
      // Visible to the operator. Also fires an SSE notification so any
      // logged-in browser can prompt the user to enter the code.
      NOTICEF("WebUI: unlock code = %s (60s) — type the first 6 chars into the browser",
              hex.c_str());
      Serial.print("\n\n==== UNLOCK CODE: ");
      Serial.print(unlock().hex6.c_str());
      Serial.println(" (valid 60s) ====\n");
      _unlock_event_pending = true;
    }

    // Check that the given proof is currently valid. Single-use: marks the
    // unlock as consumed on success.
    static bool consume_unlock_proof(const std::string& proof) {
      if (proof.empty() || unlock().hex6.empty() || unlock().consumed) return false;
      if (millis() > unlock().expires_ms) return false;
      // Constant-time-ish comparison.
      if (proof.size() != unlock().hex6.size()) return false;
      uint8_t diff = 0;
      for (size_t i = 0; i < proof.size(); i++) diff |= proof[i] ^ unlock().hex6[i];
      if (diff != 0) return false;
      unlock().consumed = true;
      return true;
    }

  private:
    // ---- Helpers ----

    static UnlockProof& unlock() {
      static UnlockProof u{"", 0, false};
      return u;
    }

    static void send_json(int code, const JsonDocument& doc) {
      String body;
      serializeJson(doc, body);
      server.send(code, "application/json", body);
    }

    static void send_error(int code, const char* msg) {
      JsonDocument doc;
      doc["error"]   = msg;
      send_json(code, doc);
    }

    // Extract bearer-token account, or send 401 and return empty.
    static LXMF::AccountId require_auth() {
      String h = server.header("Authorization");
      if (!h.startsWith("Bearer ")) {
        send_error(401, "missing_bearer");
        return {};
      }
      String hex_str = h.substring(7);
      hex_str.trim();
      LXMF::AccountId acc = AuthTokens::validate(std::string(hex_str.c_str()));
      if (acc.empty()) {
        send_error(401, "invalid_or_expired_token");
      }
      return acc;
    }

    // Read JSON body. Returns empty doc on failure (and sends a 400 to the
    // client).
    static bool read_body_json(JsonDocument& out) {
      String body = server.arg("plain");
      DeserializationError err = deserializeJson(out, body);
      if (err) {
        send_error(400, "invalid_json");
        return false;
      }
      return true;
    }

    static RNS::Bytes hex_to_bytes(const std::string& hex, size_t expected = 0) {
      RNS::Bytes b;
      if (hex.empty()) return b;
      if (expected > 0 && hex.size() != expected * 2) return b;
      b.assignHex(hex.c_str());
      return b;
    }

    // ---- Routes ----

    static void register_routes() {
      // Public
      server.on("/api/info",          HTTP_GET,  handle_info);
      // Auth
      server.on("/api/auth/login",    HTTP_POST, handle_login);
      server.on("/api/auth/logout",   HTTP_POST, handle_logout);
      // Accounts
      server.on("/api/accounts",      HTTP_POST, handle_create_account);
      server.on(UriBraces("/api/accounts/{}"), HTTP_GET, handle_get_account);
      server.on(UriBraces("/api/accounts/{}/announce"), HTTP_POST, handle_announce);
      server.on(UriBraces("/api/accounts/{}/inbox"),    HTTP_GET,  handle_inbox);
      server.on(UriBraces("/api/accounts/{}/outbox"),   HTTP_GET,  handle_outbox);
      server.on(UriBraces("/api/accounts/{}/send"),     HTTP_POST, handle_send);
      server.on(UriBraces("/api/accounts/{}/events"),   HTTP_GET,  handle_events);
      // Paths
      server.on("/api/paths/lookup",  HTTP_POST, handle_path_lookup);
    }

    static void handle_info() {
      JsonDocument doc;
      doc["fw_version"] = "lxmf-gateway-0.1";
      doc["uptime_ms"]  = (uint32_t)millis();
      doc["bootstrap"]  = false;  // Step 9 will toggle this
      doc["unlock_pending"] = !unlock().hex6.empty() && !unlock().consumed
                              && millis() < unlock().expires_ms;
      JsonArray accts = doc["accounts"].to<JsonArray>();
      for (const auto* a : LXMF::LXMFGateway::active_accounts()) {
        JsonObject obj = accts.add<JsonObject>();
        obj["id"]           = a->id;
        obj["display_name"] = a->display_name;
        obj["address"]      = a->address_hex();
      }
      send_json(200, doc);
    }

    static void handle_login() {
      JsonDocument body;
      if (!read_body_json(body)) return;
      const char* acc_str   = body["account_id"]   | "";
      const char* proof_str = body["unlock_proof"] | "";
      if (!*acc_str) { send_error(400, "missing_account_id"); return; }
      LXMF::AccountId acc_id = acc_str;
      if (!LXMF::LXMFGateway::account_by_id(acc_id)) {
        send_error(404, "unknown_account");
        return;
      }
      if (!consume_unlock_proof(proof_str)) {
        send_error(401, "unlock_required");
        return;
      }
      std::string token = AuthTokens::issue(acc_id);
      if (token.empty()) {
        send_error(500, "token_issue_failed");
        return;
      }
      JsonDocument doc;
      doc["token"]         = token;
      doc["account_id"]    = acc_id;
      doc["expires_in_s"]  = AuthTokens::DEFAULT_TTL_S;
      send_json(200, doc);
    }

    static void handle_logout() {
      String h = server.header("Authorization");
      if (h.startsWith("Bearer ")) {
        String hex_str = h.substring(7);
        hex_str.trim();
        AuthTokens::revoke(std::string(hex_str.c_str()));
      }
      server.send(204, "text/plain", "");
    }

    static void handle_create_account() {
      JsonDocument body;
      if (!read_body_json(body)) return;
      const char* name      = body["display_name"] | "";
      const char* proof_str = body["unlock_proof"] | "";
      if (!*name) { send_error(400, "missing_display_name"); return; }
      if (!consume_unlock_proof(proof_str)) {
        send_error(401, "unlock_required");
        return;
      }
      LXMF::AccountId acc_id = LXMF::LXMFGateway::create_account(name);
      if (acc_id.empty()) {
        send_error(500, "create_failed");
        return;
      }
      std::string token = AuthTokens::issue(acc_id);
      const LXMF::LXMFAccount* a = LXMF::LXMFGateway::account_by_id(acc_id);
      JsonDocument doc;
      doc["id"]      = acc_id;
      doc["address"] = a ? a->address_hex() : "";
      doc["token"]   = token;
      send_json(200, doc);
    }

    static void handle_get_account() {
      LXMF::AccountId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      const LXMF::LXMFAccount* a = LXMF::LXMFGateway::account_by_id(requested);
      if (!a) { send_error(404, "unknown_account"); return; }
      JsonDocument doc;
      doc["id"]                   = a->id;
      doc["display_name"]         = a->display_name;
      doc["address"]              = a->address_hex();
      doc["announce_interval_ms"] = a->announce_interval_ms;
      doc["inbox_size"]           = a->inbox  ? (uint32_t)a->inbox->size()  : 0;
      doc["outbox_size"]          = a->outbox ? (uint32_t)a->outbox->size() : 0;
      send_json(200, doc);
    }

    static void handle_announce() {
      LXMF::AccountId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      if (!LXMF::LXMFGateway::announce(requested)) {
        send_error(404, "unknown_account");
        return;
      }
      JsonDocument doc;
      doc["status"] = "announced";
      send_json(200, doc);
    }

    static void emit_messages_array(JsonArray arr,
                                    const std::vector<LXMF::MessageRecord>& msgs) {
      for (const auto& m : msgs) {
        JsonObject obj = arr.add<JsonObject>();
        obj["seq"]     = m.seq;
        obj["ts"]      = m.ts;
        obj["peer"]    = m.peer_hash.toHex();
        obj["title"]   = m.title;
        obj["body"]    = m.content;
        obj["sig_ok"]  = m.signature_ok;
        obj["status"]  = LXMF::outbox_status_name(m.status);
      }
    }

    static void handle_inbox() {
      LXMF::AccountId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      const LXMF::LXMFAccount* a = LXMF::LXMFGateway::account_by_id(requested);
      if (!a || !a->inbox) { send_error(404, "unknown_account"); return; }
      uint32_t since = (uint32_t)server.arg("since").toInt();
      size_t   limit = (size_t)server.arg("limit").toInt();
      if (limit == 0 || limit > 50) limit = 50;
      auto msgs = since > 0 ? a->inbox->since(since) : a->inbox->recent(limit);
      JsonDocument doc;
      JsonArray arr = doc["messages"].to<JsonArray>();
      emit_messages_array(arr, msgs);
      doc["next_since"] = a->inbox->next_seq();
      send_json(200, doc);
    }

    static void handle_outbox() {
      LXMF::AccountId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      const LXMF::LXMFAccount* a = LXMF::LXMFGateway::account_by_id(requested);
      if (!a || !a->outbox) { send_error(404, "unknown_account"); return; }
      uint32_t since = (uint32_t)server.arg("since").toInt();
      size_t   limit = (size_t)server.arg("limit").toInt();
      if (limit == 0 || limit > 50) limit = 50;
      auto msgs = since > 0 ? a->outbox->since(since) : a->outbox->recent(limit);
      JsonDocument doc;
      JsonArray arr = doc["messages"].to<JsonArray>();
      emit_messages_array(arr, msgs);
      doc["next_since"] = a->outbox->next_seq();
      send_json(200, doc);
    }

    static void handle_send() {
      LXMF::AccountId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      JsonDocument body;
      if (!read_body_json(body)) return;
      std::string to_hex  = (const char*)(body["to"]     | "");
      std::string title   = (const char*)(body["title"]  | "");
      std::string content = (const char*)(body["body"]   | "");
      if (content.empty()) { send_error(400, "missing_body"); return; }
      RNS::Bytes to = hex_to_bytes(to_hex, LXMF::HASH_LEN);
      if (to.size() != LXMF::HASH_LEN) {
        send_error(400, "invalid_destination_hash");
        return;
      }
      LXMF::MessageRecord rec;
      if (!LXMF::LXMFGateway::send(requested, to, title, content, rec)) {
        send_error(503, "send_failed");
        return;
      }
      JsonDocument doc;
      doc["queued_seq"] = rec.seq;
      doc["status"]     = LXMF::outbox_status_name(rec.status);
      send_json(202, doc);
    }

    static void handle_events() {
      // SSE-style long-poll. We park briefly, push any pending events, then
      // return so the client reconnects (EventSource auto-reconnects). This
      // pattern avoids starving the LoRa modem on the same Arduino task.
      LXMF::AccountId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      const LXMF::LXMFAccount* a = LXMF::LXMFGateway::account_by_id(requested);
      if (!a || !a->inbox) { send_error(404, "unknown_account"); return; }

      uint32_t since = (uint32_t)server.arg("since").toInt();

      server.sendHeader("Cache-Control", "no-cache");
      server.sendHeader("Connection", "keep-alive");
      server.setContentLength(CONTENT_LENGTH_UNKNOWN);
      server.send(200, "text/event-stream", "");

      // Drain anything already newer than `since`.
      auto pending = a->inbox->since(since);
      for (const auto& m : pending) {
        JsonDocument item;
        item["type"] = "incoming";
        JsonObject msg = item["msg"].to<JsonObject>();
        msg["seq"]    = m.seq;
        msg["ts"]     = m.ts;
        msg["peer"]   = m.peer_hash.toHex();
        msg["title"]  = m.title;
        msg["body"]   = m.content;
        msg["sig_ok"] = m.signature_ok;
        String line;
        serializeJson(item, line);
        server.sendContent(String("data: ") + line + "\n\n");
      }
      if (_unlock_event_pending) {
        _unlock_event_pending = false;
        server.sendContent("data: {\"type\":\"unlock_available\"}\n\n");
      }

      // Park for up to 5s, polling every 200ms, sending heartbeats and any
      // newly-arrived messages. Quick yield so the rest of the firmware
      // keeps ticking.
      uint32_t deadline = millis() + 5000;
      uint32_t last_seq = a->inbox->next_seq();
      while (millis() < deadline) {
        delay(200);
        uint32_t cur = a->inbox->next_seq();
        if (cur > last_seq) {
          auto fresh = a->inbox->since(last_seq);
          for (const auto& m : fresh) {
            JsonDocument item;
            item["type"] = "incoming";
            JsonObject msg = item["msg"].to<JsonObject>();
            msg["seq"]    = m.seq;
            msg["ts"]     = m.ts;
            msg["peer"]   = m.peer_hash.toHex();
            msg["title"]  = m.title;
            msg["body"]   = m.content;
            msg["sig_ok"] = m.signature_ok;
            String line;
            serializeJson(item, line);
            server.sendContent(String("data: ") + line + "\n\n");
          }
          last_seq = cur;
        }
        if (_unlock_event_pending) {
          _unlock_event_pending = false;
          server.sendContent("data: {\"type\":\"unlock_available\"}\n\n");
        }
      }
      server.sendContent(":heartbeat\n\n");
    }

    static void handle_path_lookup() {
      LXMF::AccountId caller = require_auth();
      if (caller.empty()) return;
      JsonDocument body;
      if (!read_body_json(body)) return;
      std::string to_hex = (const char*)(body["to"] | "");
      RNS::Bytes to = hex_to_bytes(to_hex, LXMF::HASH_LEN);
      if (to.size() != LXMF::HASH_LEN) {
        send_error(400, "invalid_destination_hash");
        return;
      }
      bool known = RNS::Transport::has_path(to);
      JsonDocument doc;
      doc["known"] = known;
      if (!known) {
        RNS::Transport::request_path(to);
        doc["requested"] = true;
      }
      send_json(200, doc);
    }

  private:
    static inline bool     _started = false;
    static inline uint32_t _last_sweep = 0;
    static inline bool     _unlock_event_pending = false;
  };

}
