#pragma once

// WebUI — HTTP/SSE bridge between browser SPAs and the LXMF gateway.
//
// Registers routes on the existing WebServer (declared in Console.h) so the
// same port-80 instance serves both the legacy console docs and our /api/*
// surface. The server is brought up by WebUI::start() once WiFi is up,
// independent of the legacy console-mode path. Both code paths share a
// `_started` guard so server.begin() is only called once.

#include <Arduino.h>
#include <WebServer.h>
#include <uri/UriBraces.h>
#include <ArduinoJson.h>
#include <Log.h>
#include <Transport.h>
#include <deque>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <freertos/semphr.h>

#include "../LXMF/LXMFGateway.h"
#include "../LXMF/LXMFTypes.h"
#include "../LXMF/AnnounceLog.h"
#include "AuthTokens.h"
#include "BootCounter.h"
#include "PasswordHash.h"
#include "SPAEmbedded.h"

// EEPROM helpers + WiFi config constants from the existing firmware.
// Used by the bootstrap-mode WiFi configure endpoint.
#include "../Config.h"   // WR_WIFI_OFF/STA/AP, config_addr()
#include "../ROM.h"      // ADDR_CONF_SSID, ADDR_CONF_PSK
extern void eeprom_update(int mapped_addr, uint8_t byte);
extern void wr_conf_save(uint8_t mode);
extern bool eeprom_have_conf();
extern uint32_t lora_freq;
extern uint32_t lora_bw;
extern int      lora_sf;
extern int      lora_cr;
extern int      lora_txp;
extern bool     radio_online;
// Radio activity counters (defined in Config.h / RNode_Firmware.ino).
// Used to expose live transmit/receive stats so callers can confirm the
// radio is actually doing work rather than just reporting `online: true`.
extern uint32_t stat_rx;          // total packets received since boot
extern uint32_t stat_tx;          // total packets transmitted since boot
extern int      last_rssi;        // RSSI of the last received packet (dBm)
extern uint8_t  last_snr_raw;     // SNR of the last received packet (raw scale)
extern int      noise_floor;      // measured noise floor (dBm)
extern float    airtime;          // short-term channel utilisation as 0..1
extern float    longterm_airtime; // long-term (1h) channel utilisation as 0..1
extern float    st_airtime_limit; // short-term duty-cycle cap (0..1, 0=disabled)
extern float    lt_airtime_limit; // long-term duty-cycle cap (0..1, 0=disabled)
extern bool     airtime_lock;     // true when current airtime exceeds the cap; TX blocked

#include <algorithm>
#include <vector>
#include <string>

extern WebServer server;          // declared in Console.h
extern bool      wifi_initialized;
extern microStore::FileSystem filesystem;

namespace Web {

  // Single-use 6-hex-char identity code generated by a button press on
  // the device. Required for /api/identities (create), /api/auth/login,
  // /api/wifi/configure, /api/radio. Proves physical possession of the
  // device — same role as PSK-on-back-of-router but ephemeral.
  // Lives only in RAM; expires after IDENTITY_CODE_TTL_MS.
  struct IdentityCode {
    std::string  hex6;        // first 6 chars of a 16-byte random token
    uint32_t     expires_ms;  // millis() snapshot
    bool         consumed;
  };

  class WebUI {
  public:
    static constexpr uint32_t IDENTITY_CODE_TTL_MS = 60UL * 1000UL;

    // Set by the firmware setup() path when WiFi failed to come up in STA
    // mode and we fell back to softAP. Toggles /api/wifi/* into the
    // unauthenticated bootstrap configuration mode.
    static inline bool bootstrap_mode = false;

    // Called once at boot, after WiFi STA is up. Idempotent.
    static void start() {
      if (_started) return;
      _started = true;
      AuthTokens::load();
      BootCounter::init();  // emit the log line; current() is otherwise lazy
      register_routes();
      static const char* collect[] = {"Authorization"};
      server.collectHeaders(collect, sizeof(collect)/sizeof(collect[0]));
      server.begin();
      NOTICE("WebUI: listening on port 80");
    }

    // Main-loop hook. Used only for the token-expiry sweep now; the
    // server.handleClient() loop runs in its own FreeRTOS task pinned to
    // core 0 (see start_task() below). The main loop still calls this so
    // the existing RNode_Firmware.ino integration doesn't need to know
    // about the task split.
    static void loop() {
      if (!_started) return;
      uint32_t now = millis();
      if (now - _last_sweep > 60000) {
        _last_sweep = now;
        if (acquire_rns_lock(50)) {
          AuthTokens::sweep_expired();
          if (id_code().expires_ms != 0 && now > id_code().expires_ms) {
            id_code().hex6.clear();
            id_code().expires_ms = 0;
            id_code().consumed = false;
          }
          release_rns_lock();
        }
      }
    }

    // RNS state mutex. Shared between the WebServer task (which calls
    // into LXMFGateway / Identity / Destination / Inbox / etc. when
    // handling requests) and the main loop (which runs the RNS+LXMF
    // event loop). RNS is NOT reentrant; without serialisation a request
    // arriving mid-flight while the main loop is mutating path tables
    // races and crashes the device. The mutex is recursive so a handler
    // that holds it can call any number of nested RNS helpers without
    // deadlocking itself.
    static SemaphoreHandle_t& rns_lock() {
      static SemaphoreHandle_t s = nullptr;
      if (!s) s = xSemaphoreCreateRecursiveMutex();
      return s;
    }
    static bool acquire_rns_lock(uint32_t timeout_ms = portMAX_DELAY) {
      return xSemaphoreTakeRecursive(rns_lock(),
                                     timeout_ms == portMAX_DELAY ? portMAX_DELAY
                                                                 : pdMS_TO_TICKS(timeout_ms))
             == pdTRUE;
    }
    static void release_rns_lock() {
      xSemaphoreGiveRecursive(rns_lock());
    }

    // RAII helper for handlers / main-loop code that wants
    // mutex-guarded access to RNS state.
    struct RnsLockGuard {
      bool ok;
      explicit RnsLockGuard(uint32_t timeout_ms = portMAX_DELAY)
        : ok(acquire_rns_lock(timeout_ms)) {}
      ~RnsLockGuard() { if (ok) release_rns_lock(); }
      explicit operator bool() const { return ok; }
    };

    // FreeRTOS task body. Calls server.handleClient() in a tight loop
    // with a brief vTaskDelay between iterations so the FreeRTOS
    // scheduler can preempt for higher-priority work. Each call takes
    // the rns_lock briefly while routing through the handlers; the
    // handlers can also hold the lock for their own RNS calls.
    static void web_task(void* /*arg*/) {
      NOTICE("WebUI: web_task started on core 0");
      while (true) {
        if (_started) {
          if (acquire_rns_lock(20)) {
            server.handleClient();
            release_rns_lock();
          }
        }
        // 5ms gives the main loop plenty of opportunity to acquire the
        // lock between requests. Without this the WebServer task can
        // hog the lock if requests come in rapid succession.
        vTaskDelay(pdMS_TO_TICKS(5));
      }
    }

    // Spawn the WebServer task. Call once from setup() after WiFi is up
    // and start() has been called. Pinned to core 0 (PRO_CPU) — same
    // core as WiFi / lwIP — so HTTP traffic stays out of the radio
    // event loop's path on core 1.
    static void start_task() {
      static TaskHandle_t handle = nullptr;
      if (handle) return;   // already running
      xTaskCreatePinnedToCore(
        web_task,           // task function
        "webui",            // human-readable name
        8192,               // stack bytes — handlers can use a few KB for JSON
        nullptr,            // task arg (unused)
        1,                  // priority — same as the loopTask
        &handle,            // task handle
        0                   // core 0 (PRO_CPU)
      );
    }

    // Called from the button handler in RNode_Firmware.ino when the user
    // short-presses the device's USR1 button. Generates a fresh 16-byte
    // random; the first 6 hex chars are the proof we'll demand on the next
    // auth-sensitive request. The full hex is printed to serial so the
    // operator can see it (OLED integration is a later step).
    static void on_button_request_identity_code() {
      RNS::Bytes b = RNS::Cryptography::random(16);
      std::string hex = b.toHex();
      id_code().hex6      = hex.substr(0, 6);
      id_code().expires_ms = millis() + IDENTITY_CODE_TTL_MS;
      id_code().consumed  = false;
      // Visible to the operator. Also fires an SSE notification so any
      // logged-in browser can prompt the user to enter the code.
      NOTICEF("WebUI: identity code = %s (60s) — type the first 6 chars into the browser",
              hex.c_str());
      Serial.print("\n\n==== IDENTITY CODE: ");
      Serial.print(id_code().hex6.c_str());
      Serial.println(" (valid 60s) ====\n");
      _id_code_event_pending = true;
    }

    // Display accessors so the OLED renderer can show the identity code
    // without coupling Display.h to the rest of the WebUI internals. Read
    // each frame; returns empty / 0 if no identity code is pending.
    static const std::string& identity_code_for_display() {
      static const std::string empty;
      auto& u = id_code();
      if (u.hex6.empty() || u.consumed) return empty;
      if (millis() > u.expires_ms) return empty;
      return u.hex6;
    }

    static uint32_t identity_code_remaining_ms() {
      auto& u = id_code();
      if (u.hex6.empty() || u.consumed) return 0;
      uint32_t now = millis();
      if (now > u.expires_ms) return 0;
      return u.expires_ms - now;
    }

    // Check that the given proof is currently valid. Single-use: marks the
    // unlock as consumed on success.
    static bool consume_identity_code(const std::string& proof) {
      if (proof.empty() || id_code().hex6.empty() || id_code().consumed) return false;
      if (millis() > id_code().expires_ms) return false;
      // Constant-time-ish comparison.
      if (proof.size() != id_code().hex6.size()) return false;
      uint8_t diff = 0;
      for (size_t i = 0; i < proof.size(); i++) diff |= proof[i] ^ id_code().hex6[i];
      if (diff != 0) return false;
      id_code().consumed = true;
      return true;
    }

    // Explain why an identity-code proof did or didn't work. Returns
    // nullptr on success (proof valid, code consumed). On failure returns
    // a human-readable string the caller can shove into the JSON error
    // response so the UI can show something better than just
    // "identity_code_required". Same single-use side-effect as
    // consume_identity_code on success.
    static const char* explain_identity_code_failure(const std::string& proof) {
      auto& u = id_code();
      const uint32_t now = millis();
      if (u.hex6.empty()) {
        return "No identity code is pending on this device. Press the device's program button: long-press (~1s), release, then short-press within 2s. Read the 6 hex chars from the OLED or serial console.";
      }
      if (u.consumed) {
        return "The pending identity code was already used. Press the device button again to generate a fresh one.";
      }
      if (now > u.expires_ms) {
        return "The identity code expired (60s lifetime). Press the device button again to generate a fresh one.";
      }
      if (proof.empty()) {
        return "Identity code is required for this operation. Type the 6 hex chars currently displayed on the device.";
      }
      if (proof.size() != u.hex6.size()) {
        return "Identity code is the wrong length — it should be 6 hex characters.";
      }
      uint8_t diff = 0;
      for (size_t i = 0; i < proof.size(); i++) diff |= proof[i] ^ u.hex6[i];
      if (diff != 0) {
        return "Identity code didn't match — check you've read it from the correct device's OLED.";
      }
      u.consumed = true;
      return nullptr;
    }

  private:
    // ---- Helpers ----

    static IdentityCode& id_code() {
      static IdentityCode u{"", 0, false};
      return u;
    }

    static void send_json(int code, const JsonDocument& doc) {
      String body;
      serializeJson(doc, body);
      server.send(code, "application/json", body);
    }

    static void send_error(int code, const char* msg) {
      JsonDocument doc;
      doc["error"]   = msg;
      send_json(code, doc);
    }

    // Same shape as send_error but also includes a free-text `message`
    // field the SPA can display directly to the user.
    static void send_error_with_message(int code, const char* err, const char* msg) {
      JsonDocument doc;
      doc["error"]   = err;
      doc["message"] = msg;
      send_json(code, doc);
    }

    // Extract bearer-token identity from the Authorization header. Falls
    // back to a `token` query-string param so EventSource (which can't set
    // headers) can authenticate. Sends 401 and returns empty on failure.
    static LXMF::IdentityId require_auth() {
      std::string token;
      String h = server.header("Authorization");
      if (h.startsWith("Bearer ")) {
        String hex_str = h.substring(7);
        hex_str.trim();
        token = std::string(hex_str.c_str());
      } else if (server.hasArg("token")) {
        token = std::string(server.arg("token").c_str());
      } else {
        send_error(401, "missing_bearer");
        return {};
      }
      LXMF::IdentityId acc = AuthTokens::validate(token);
      if (acc.empty()) {
        send_error(401, "invalid_or_expired_token");
      }
      return acc;
    }

    // Read JSON body. Returns empty doc on failure (and sends a 400 to the
    // client).
    static bool read_body_json(JsonDocument& out) {
      String body = server.arg("plain");
      DeserializationError err = deserializeJson(out, body);
      if (err) {
        send_error(400, "invalid_json");
        return false;
      }
      return true;
    }

    static RNS::Bytes hex_to_bytes(const std::string& hex, size_t expected = 0) {
      RNS::Bytes b;
      if (hex.empty()) return b;
      if (expected > 0 && hex.size() != expected * 2) return b;
      b.assignHex(hex.c_str());
      return b;
    }

    // ---- Routes ----

    static void register_routes() {
      // SPA — single embedded HTML file, served gzipped at / and /index.html
      server.on("/",            HTTP_GET, handle_spa);
      server.on("/index.html",  HTTP_GET, handle_spa);
      // Public
      server.on("/api/info",          HTTP_GET,  handle_info);
      // Auth
      server.on("/api/auth/login",    HTTP_POST, handle_login);
      server.on("/api/auth/logout",   HTTP_POST, handle_logout);
      // Identities
      server.on("/api/identities",      HTTP_POST, handle_create_identity);
      server.on(UriBraces("/api/identities/{}"), HTTP_GET,    handle_get_identity);
      server.on(UriBraces("/api/identities/{}"), HTTP_DELETE, handle_delete_identity);
      server.on(UriBraces("/api/identities/{}/delete"), HTTP_POST, handle_delete_identity);
      server.on(UriBraces("/api/identities/{}/announce"), HTTP_POST, handle_announce);
      server.on(UriBraces("/api/identities/{}/settings"), HTTP_POST, handle_identity_settings);
      // Announces (recent LXMF endpoint announces seen by the device)
      server.on("/api/announces",     HTTP_GET, handle_announces);
      // System — full wipe, gated by identity_code (physical presence).
      // Only path to recovery if every identity password is forgotten.
      server.on("/api/system/factory_reset", HTTP_POST, handle_factory_reset);
      server.on("/api/system/transport",     HTTP_POST, handle_transport_toggle);
      server.on(UriBraces("/api/identities/{}/inbox"),    HTTP_GET,  handle_inbox);
      server.on(UriBraces("/api/identities/{}/outbox"),   HTTP_GET,  handle_outbox);
      server.on(UriBraces("/api/identities/{}/send"),     HTTP_POST, handle_send);
      server.on(UriBraces("/api/identities/{}/events"),   HTTP_GET,  handle_events);
      server.on(UriBraces("/api/identities/{}/state"),    HTTP_GET,  handle_state);
      server.on(UriBraces("/api/identities/{}/conversations/{}"),
                HTTP_DELETE, handle_clear_conversation);
      // Paths
      server.on("/api/paths",         HTTP_GET,  handle_paths_list);
      server.on("/api/paths/lookup",  HTTP_POST, handle_path_lookup);
      // WiFi config — gated by bearer token OR identity_code in body.
      // Reboots on save.
      server.on("/api/wifi/scan",     HTTP_GET,  handle_wifi_scan);
      server.on("/api/wifi/configure",HTTP_POST, handle_wifi_configure);
      // Radio config — read requires bearer auth; write/reset require
      // bearer OR identity_code. Both write paths reboot on success.
      server.on("/api/radio",         HTTP_GET,  handle_radio_get);
      server.on("/api/radio",         HTTP_POST, handle_radio_set);
      server.on("/api/radio/reset",   HTTP_POST, handle_radio_reset);
      server.on("/api/radio/airtime", HTTP_POST, handle_radio_airtime);
    }

    static void handle_spa() {
      server.sendHeader("Content-Encoding", "gzip");
      // no-store, not no-cache: no-cache lets the browser keep a copy and
      // revalidate, but our handler doesn't implement 304, so stale SPAs
      // get served. no-store guarantees a fresh fetch every load.
      server.sendHeader("Cache-Control", "no-store");
      server.send_P(200, "text/html",
                    reinterpret_cast<const char*>(Web::SPA_HTML_GZ),
                    Web::SPA_HTML_GZ_LEN);
    }

    static void handle_info() {
      JsonDocument doc;
      doc["fw_version"] = "lxmf-gateway-0.1";
      doc["uptime_ms"]  = (uint32_t)millis();
      doc["bootstrap"]  = bootstrap_mode;
      doc["identity_code_pending"] = !id_code().hex6.empty() && !id_code().consumed
                              && millis() < id_code().expires_ms;
      JsonArray accts = doc["identities"].to<JsonArray>();
      for (const auto* a : LXMF::LXMFGateway::active_identities()) {
        JsonObject obj = accts.add<JsonObject>();
        obj["id"]           = a->id;
        obj["display_name"] = a->display_name;
        obj["address"]      = a->address_hex();
      }
      // Radio + transport status. Surfaced here so the SPA can render a
      // single status indicator without an extra round-trip on every
      // page load.
      JsonObject radio = doc["radio"].to<JsonObject>();
      radio["online"]           = radio_online;
      radio["have_conf"]        = eeprom_have_conf();
      radio["frequency"]        = (uint32_t)lora_freq;
      radio["bandwidth"]        = (uint32_t)lora_bw;
      radio["spreading_factor"] = lora_sf;
      radio["coding_rate"]      = lora_cr;
      radio["tx_power"]         = lora_txp;
      // Surface radio-init failure cause when it happened. Most common
      // cause is a wrong-variant flash — see startRadio() in
      // RNode_Firmware.ino. The SPA can show a banner / settings panel
      // warning when error_reason is present.
      if (radio_error_reason) {
        radio["error_reason"]   = radio_error_reason;
      }
      if (radio_error_expected_chip) {
        radio["expected_chip"]  = radio_error_expected_chip;
      }
      // Activity counters so callers can verify the radio is actually
      // doing work (not just "online"). stat_rx / stat_tx are packet
      // counts since boot — poll twice with a delta to see if the
      // radio is actively transmitting/receiving. airtime is the
      // short-term channel utilisation fraction (0..1).
      JsonObject stats = radio["stats"].to<JsonObject>();
      // Reticulum stack counts — these get incremented on every packet
      // through Transport::outbound / Transport::inbound and are the most
      // accurate "is the radio doing work" signal. The legacy stat_rx /
      // stat_tx variables from the upstream RNode firmware are unused
      // (never incremented in this codebase).
      stats["rx_packets"]         = (uint32_t)RNS::Transport::packets_received();
      stats["tx_packets"]         = (uint32_t)RNS::Transport::packets_sent();
      stats["destinations_seen"]  = (uint32_t)RNS::Transport::destinations_added();
      stats["last_rssi_dbm"]      = last_rssi;
      stats["last_snr_raw"]       = last_snr_raw;
      stats["noise_floor_dbm"]    = noise_floor;
      stats["airtime_pct"]          = (int)(airtime * 100);
      stats["longterm_airtime_pct"] = (int)(longterm_airtime * 100);
      // Duty-cycle caps. 0 means "no limit" (illegal in regulated bands).
      // The default at boot is 0.01 (1%) to stay within ETSI 868 MHz limits.
      stats["airtime_limit_pct"]    = (int)(st_airtime_limit * 100);
      stats["longterm_airtime_limit_pct"] = (int)(lt_airtime_limit * 100);
      // True iff TX is currently being blocked by the airtime lock —
      // useful for "why isn't my message going out" diagnostics.
      stats["airtime_locked"]       = (bool)airtime_lock;
      JsonObject transport = doc["transport"].to<JsonObject>();
      transport["enabled"]      = RNS::Reticulum::transport_enabled();
      // TODO microReticulum doesn't yet expose live path/packet counters
      // through a stable static getter. Add an accessor on the local
      // clone branch when we want to surface them in the SPA.
      send_json(200, doc);
    }

    static void handle_login() {
      JsonDocument body;
      if (!read_body_json(body)) return;
      const char* acc_str = body["identity_id"] | "";
      const char* pw_str  = body["password"]   | "";
      if (!*acc_str) { send_error(400, "missing_identity_id"); return; }
      if (!*pw_str)  { send_error(400, "missing_password");   return; }
      LXMF::IdentityId iden_id = acc_str;
      if (!LXMF::LXMFGateway::identity_by_id(iden_id)) {
        send_error(404, "unknown_identity");
        return;
      }
      // Knowledge-factor only — physical-presence button gesture is
      // explicitly NOT a path to login because a stolen device could
      // otherwise be unlocked by anyone with hands on it.
      if (!LXMF::LXMFGateway::check_password(iden_id, pw_str, PasswordHash::verify)) {
        send_error(401, "invalid_password");
        return;
      }
      std::string token = AuthTokens::issue(iden_id);
      if (token.empty()) {
        send_error(500, "token_issue_failed");
        return;
      }
      JsonDocument doc;
      doc["token"]         = token;
      doc["identity_id"]    = iden_id;
      doc["expires_in_s"]  = AuthTokens::DEFAULT_TTL_S;
      send_json(200, doc);
    }

    static void handle_logout() {
      String h = server.header("Authorization");
      if (h.startsWith("Bearer ")) {
        String hex_str = h.substring(7);
        hex_str.trim();
        AuthTokens::revoke(std::string(hex_str.c_str()));
      }
      server.send(204, "text/plain", "");
    }

    static void handle_create_identity() {
      JsonDocument body;
      if (!read_body_json(body)) return;
      const char* name      = body["display_name"]     | "";
      const char* proof_str = body["identity_code"]    | "";
      const char* pw        = body["password"]         | "";
      const char* pw_conf   = body["password_confirm"] | "";
      if (!*name) { send_error(400, "missing_display_name"); return; }
      if (strlen(pw) < PasswordHash::MIN_PASSWORD_LEN) {
        send_error(400, "password_too_short");
        return;
      }
      if (strcmp(pw, pw_conf) != 0) {
        send_error(400, "password_mismatch");
        return;
      }
      // Physical-presence proof required for identity creation —
      // the password becomes the login factor afterwards, but creating
      // identities on a stolen / network-reachable device should not be
      // possible without someone physically present at the device.
      const char* code_err = explain_identity_code_failure(proof_str);
      if (code_err) {
        send_error_with_message(401, "identity_code_required", code_err);
        return;
      }
      LXMF::IdentityId iden_id = LXMF::LXMFGateway::create_identity(
          name, pw, PasswordHash::derive, PasswordHash::new_salt);
      if (iden_id.empty()) {
        send_error(500, "create_failed");
        return;
      }
      std::string token = AuthTokens::issue(iden_id);
      const LXMF::LXMFIdentity* a = LXMF::LXMFGateway::identity_by_id(iden_id);
      JsonDocument doc;
      doc["id"]      = iden_id;
      doc["address"] = a ? a->address_hex() : "";
      doc["token"]   = token;
      send_json(200, doc);
    }

    static void handle_get_identity() {
      LXMF::IdentityId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      const LXMF::LXMFIdentity* a = LXMF::LXMFGateway::identity_by_id(requested);
      if (!a) { send_error(404, "unknown_identity"); return; }
      JsonDocument doc;
      doc["id"]                   = a->id;
      doc["display_name"]         = a->display_name;
      doc["address"]              = a->address_hex();
      doc["announce_interval_ms"] = a->announce_interval_ms;
      doc["inbox_size"]           = a->inbox  ? (uint32_t)a->inbox->size()  : 0;
      doc["outbox_size"]          = a->outbox ? (uint32_t)a->outbox->size() : 0;
      // Time until the next *auto* announce. 0 when auto-announce is
      // disabled or when the timer has already elapsed (next loop tick
      // will announce). Lets the SPA drive a countdown badge.
      uint32_t next_in = 0;
      if (a->announce_interval_ms > 0) {
        uint32_t elapsed = millis() - a->last_announce_ms;
        next_in = (elapsed >= a->announce_interval_ms) ? 0 : (a->announce_interval_ms - elapsed);
      }
      doc["next_announce_in_ms"]  = next_in;
      send_json(200, doc);
    }

    static void handle_delete_identity() {
      LXMF::IdentityId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      AuthTokens::revoke_for_identity(requested);
      if (!LXMF::LXMFGateway::delete_identity(requested)) {
        send_error(404, "unknown_identity");
        return;
      }
      server.send(204, "text/plain", "");
    }

    // Toggle Reticulum transport mode on or off at runtime. Persists
    // the choice to /lxmf/transport.json so it survives reboots.
    // Requires an authenticated session — anyone with a token can flip
    // it for now, since we don't have per-identity admin yet.
    static void handle_transport_toggle() {
      LXMF::IdentityId caller = require_auth();
      if (caller.empty()) return;
      JsonDocument body;
      if (!read_body_json(body)) return;
      if (!body["enabled"].is<bool>()) {
        send_error_with_message(400, "missing_enabled",
            "Request must include {enabled: true|false}.");
        return;
      }
      bool enabled = body["enabled"].as<bool>();
      RNS::Reticulum::transport_enabled(enabled);
      // Persist for next boot. Tiny JSON file alongside the rest of
      // the gateway's state in /lxmf.
      JsonDocument persist;
      persist["enabled"] = enabled;
      String s; serializeJson(persist, s);
      filesystem.writeFile("/lxmf/transport.json",
                           (const uint8_t*)s.c_str(), s.length());
      NOTICEF("WebUI: transport_enabled set to %s by %s",
              enabled ? "true" : "false", caller.c_str());
      JsonDocument doc;
      doc["enabled"] = enabled;
      send_json(200, doc);
    }

    static void handle_factory_reset() {
      JsonDocument body;
      if (!read_body_json(body)) return;
      // Physical-presence required, regardless of any active session —
      // factory reset wipes ALL identities and all messages, so the
      // proof-of-possession bar applies just like identity creation.
      const char* proof = body["identity_code"] | "";
      const char* code_err = explain_identity_code_failure(proof);
      if (code_err) {
        send_error_with_message(401, "identity_code_required", code_err);
        return;
      }
      NOTICE("WebUI: factory reset triggered — wiping /lxmf and rebooting");

      // Walk every active identity, deregister + remove its files.
      // Iterate by value-copy because delete_identity mutates the slot.
      std::vector<LXMF::IdentityId> ids;
      for (const auto* a : LXMF::LXMFGateway::active_identities()) {
        if (a) ids.push_back(a->id);
      }
      for (const auto& id : ids) LXMF::LXMFGateway::delete_identity(id);

      // Belt-and-braces: remove anything else in /lxmf/.
      filesystem.remove("/lxmf/auth_tokens.json");
      filesystem.remove("/lxmf/button_unlock.json");
      // We deliberately do NOT touch the Reticulum transport identity
      // (stored at /transport_identity) or path_store — those are
      // device-level state, not per-identity secrets.

      JsonDocument doc;
      doc["status"]  = "wiped";
      doc["restart"] = true;
      send_json(200, doc);
      delay(500);
      ESP.restart();
    }

    // DELETE /api/identities/{id}/conversations/{peer_hex}
    // Bearer-auth gated. Removes every inbox + outbox record for this
    // identity whose peer_hash matches peer_hex. Rewrites the JSONL
    // spool. Identity itself, keys, and other peers are untouched.
    static void handle_clear_conversation() {
      LXMF::IdentityId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      std::string peer_hex = std::string(server.pathArg(1).c_str());
      RNS::Bytes peer = hex_to_bytes(peer_hex, LXMF::HASH_LEN);
      if (peer.size() != LXMF::HASH_LEN) {
        char msg[120];
        snprintf(msg, sizeof(msg),
                 "Peer address must be 32 hex characters (got %u).",
                 (unsigned)peer_hex.size());
        send_error_with_message(400, "invalid_peer_hash", msg);
        return;
      }
      const LXMF::LXMFIdentity* a = LXMF::LXMFGateway::identity_by_id(requested);
      if (!a) { send_error(404, "unknown_identity"); return; }
      size_t inbox_removed  = a->inbox  ? a->inbox->purge_peer(peer)  : 0;
      size_t outbox_removed = a->outbox ? a->outbox->purge_peer(peer) : 0;
      NOTICEF("WebUI: cleared conversation %s <-> %s (inbox=%u outbox=%u)",
              requested.c_str(), peer_hex.c_str(),
              (unsigned)inbox_removed, (unsigned)outbox_removed);
      JsonDocument doc;
      doc["inbox_removed"]  = (uint32_t)inbox_removed;
      doc["outbox_removed"] = (uint32_t)outbox_removed;
      send_json(200, doc);
    }

    static void handle_announces() {
      if (require_auth().empty()) return;
      const auto& ring = LXMF::AnnounceLog::announces();
      JsonDocument doc;
      JsonArray arr = doc["announces"].to<JsonArray>();
      uint32_t now = millis();
      for (auto it = ring.rbegin(); it != ring.rend(); ++it) {
        JsonObject obj = arr.add<JsonObject>();
        obj["dest"]         = it->destination.toHex();
        obj["display_name"] = it->display_name;
        obj["age_ms"]       = (uint32_t)(now - it->received_ms);
      }
      doc["count"] = (uint32_t)ring.size();
      send_json(200, doc);
    }

    static void handle_announce() {
      LXMF::IdentityId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      if (!LXMF::LXMFGateway::announce(requested)) {
        send_error(404, "unknown_identity");
        return;
      }
      JsonDocument doc;
      doc["status"] = "announced";
      send_json(200, doc);
    }

    static void handle_identity_settings() {
      LXMF::IdentityId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      JsonDocument body;
      if (!read_body_json(body)) return;
      // Per-identity settings. Currently just the auto-announce interval;
      // more knobs will plug in here as we add them.
      if (body["announce_interval_ms"].is<JsonVariant>()) {
        uint32_t ms = (uint32_t)(body["announce_interval_ms"] | 0);
        // 0 == disabled. Otherwise clamp to a sane minimum (10s) so a
        // typo can't melt the radio's duty-cycle budget.
        if (ms != 0 && ms < 10000) ms = 10000;
        if (!LXMF::LXMFGateway::set_announce_interval(requested, ms)) {
          send_error(404, "unknown_identity");
          return;
        }
      }
      const LXMF::LXMFIdentity* a = LXMF::LXMFGateway::identity_by_id(requested);
      JsonDocument doc;
      doc["id"]                   = requested;
      doc["announce_interval_ms"] = a ? a->announce_interval_ms : 0;
      send_json(200, doc);
    }

    static void emit_messages_array(JsonArray arr,
                                    const std::vector<LXMF::MessageRecord>& msgs) {
      for (const auto& m : msgs) {
        JsonObject obj = arr.add<JsonObject>();
        obj["seq"]         = m.seq;
        obj["ts"]          = m.ts;
        obj["boot_epoch"]  = m.boot_epoch;
        obj["received_ms"] = m.received_ms;
        obj["peer"]        = m.peer_hash.toHex();
        obj["title"]       = m.title;
        obj["body"]        = m.content;
        obj["sig_ok"]      = m.signature_ok;
        obj["status"]      = LXMF::outbox_status_name(m.status);
      }
    }

    static void handle_inbox() {
      LXMF::IdentityId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      const LXMF::LXMFIdentity* a = LXMF::LXMFGateway::identity_by_id(requested);
      if (!a || !a->inbox) { send_error(404, "unknown_identity"); return; }
      uint32_t since = (uint32_t)server.arg("since").toInt();
      size_t   limit = (size_t)server.arg("limit").toInt();
      if (limit == 0 || limit > 50) limit = 50;
      auto msgs = since > 0 ? a->inbox->since(since) : a->inbox->recent(limit);
      JsonDocument doc;
      JsonArray arr = doc["messages"].to<JsonArray>();
      emit_messages_array(arr, msgs);
      doc["next_since"] = a->inbox->next_seq();
      send_json(200, doc);
    }

    static void handle_outbox() {
      LXMF::IdentityId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      const LXMF::LXMFIdentity* a = LXMF::LXMFGateway::identity_by_id(requested);
      if (!a || !a->outbox) { send_error(404, "unknown_identity"); return; }
      uint32_t since = (uint32_t)server.arg("since").toInt();
      size_t   limit = (size_t)server.arg("limit").toInt();
      if (limit == 0 || limit > 50) limit = 50;
      auto msgs = since > 0 ? a->outbox->since(since) : a->outbox->recent(limit);
      JsonDocument doc;
      JsonArray arr = doc["messages"].to<JsonArray>();
      emit_messages_array(arr, msgs);
      doc["next_since"] = a->outbox->next_seq();
      send_json(200, doc);
    }

    static void handle_send() {
      LXMF::IdentityId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      JsonDocument body;
      if (!read_body_json(body)) return;
      std::string to_hex  = (const char*)(body["to"]      | "");
      std::string title   = (const char*)(body["title"]   | "");
      // The SPA sends `content`; legacy / external clients may still send
      // `body`. Accept either, preferring `content`.
      std::string content = (const char*)(body["content"] | (body["body"] | ""));
      if (content.empty()) {
        send_error_with_message(400, "missing_content",
            "Message body is empty. Type something in the compose box before sending.");
        return;
      }
      RNS::Bytes to = hex_to_bytes(to_hex, LXMF::HASH_LEN);
      if (to.size() != LXMF::HASH_LEN) {
        char msg[120];
        snprintf(msg, sizeof(msg),
                 "Destination address must be 32 hex characters (got %u).",
                 (unsigned)to_hex.size());
        send_error_with_message(400, "invalid_destination_hash", msg);
        return;
      }
      LXMF::MessageRecord rec;
      const char* err = nullptr;
      if (!LXMF::LXMFGateway::send(requested, to, title, content, rec, &err)) {
        send_error_with_message(503, "send_failed",
                                err ? err : "Send failed for an unknown reason.");
        return;
      }
      JsonDocument doc;
      doc["queued_seq"] = rec.seq;
      doc["status"]     = LXMF::outbox_status_name(rec.status);
      send_json(202, doc);
    }

    static void handle_state() {
      // One-shot snapshot the SPA fetches on first connect (and on
      // SSE-reconnect after a long drop). Returns the conversation list,
      // both announce rings, and the since markers the SPA passes to the
      // SSE handler so deltas resume cleanly without duplicating events.
      LXMF::IdentityId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      const LXMF::LXMFIdentity* a = LXMF::LXMFGateway::identity_by_id(requested);
      if (!a) { send_error(404, "unknown_identity"); return; }

      JsonDocument doc;
      // Identity self-info.
      JsonObject me = doc["identity"].to<JsonObject>();
      me["id"]                   = a->id;
      me["display_name"]         = a->display_name;
      me["address"]              = a->address_hex();
      me["announce_interval_ms"] = a->announce_interval_ms;
      {
        uint32_t next_in = 0;
        if (a->announce_interval_ms > 0) {
          uint32_t elapsed = millis() - a->last_announce_ms;
          next_in = (elapsed >= a->announce_interval_ms) ? 0 : (a->announce_interval_ms - elapsed);
        }
        me["next_announce_in_ms"] = next_in;
      }

      // Conversation list: group recent inbox+outbox messages by peer.
      // Each conversation gets last_msg/last_ts/direction and a message
      // slice. The SPA can request more on demand via the existing
      // /inbox?since= and /outbox?since= endpoints.
      JsonArray convs = doc["conversations"].to<JsonArray>();
      // Walk inbox + outbox once, keeping the latest record per peer plus
      // the full message slice. Build a small lookup map<peer_hex, idx>.
      struct ConvAccum {
        std::string peer_hex;
        std::vector<LXMF::MessageRecord> msgs;  // chronological
      };
      std::vector<ConvAccum> convs_list;
      auto upsert = [&](const LXMF::MessageRecord& m) {
        std::string ph = m.peer_hash.toHex();
        for (auto& c : convs_list) {
          if (c.peer_hex == ph) { c.msgs.push_back(m); return; }
        }
        convs_list.push_back({ph, {m}});
      };
      if (a->inbox)  for (const auto& m : a->inbox->recent(64))  upsert(m);
      if (a->outbox) for (const auto& m : a->outbox->recent(64)) upsert(m);
      // Order by (boot_epoch, received_ms) — see LXMFTypes.h. boot_epoch
      // makes the tuple monotonic across reboots; received_ms breaks
      // ties within a boot. ts is for display only.
      auto less_key = [](const LXMF::MessageRecord& x, const LXMF::MessageRecord& y){
        if (x.boot_epoch != y.boot_epoch) return x.boot_epoch < y.boot_epoch;
        return x.received_ms < y.received_ms;
      };
      for (auto& c : convs_list) {
        std::sort(c.msgs.begin(), c.msgs.end(), less_key);
      }
      std::sort(convs_list.begin(), convs_list.end(),
                [&](const ConvAccum& x, const ConvAccum& y){
                  if (x.msgs.empty()) return false;
                  if (y.msgs.empty()) return true;
                  return less_key(y.msgs.back(), x.msgs.back());
                });
      for (const auto& c : convs_list) {
        JsonObject co = convs.add<JsonObject>();
        co["peer"] = c.peer_hex;
        if (!c.msgs.empty()) {
          const auto& last = c.msgs.back();
          co["last_ts"]          = last.ts;
          co["last_boot_epoch"]  = last.boot_epoch;
          co["last_received_ms"] = last.received_ms;
          co["last_body"]        = last.content;
          co["last_in"]          = last.incoming;
        }
        JsonArray msgs = co["messages"].to<JsonArray>();
        for (const auto& m : c.msgs) {
          JsonObject mo = msgs.add<JsonObject>();
          mo["seq"]         = m.seq;
          mo["ts"]          = m.ts;
          mo["boot_epoch"]  = m.boot_epoch;
          mo["received_ms"] = m.received_ms;
          mo["title"]       = m.title;
          mo["body"]        = m.content;
          mo["in"]          = m.incoming;
          mo["sig_ok"]      = m.signature_ok;
          mo["status"]      = LXMF::outbox_status_name(m.status);
        }
      }

      // Announce ring snapshot. The SPA uses received_ms of the newest
      // entry as the SSE announces_since marker.
      JsonArray announces = doc["announces"].to<JsonArray>();
      uint32_t announces_high_water = 0;
      for (const auto& rec : LXMF::AnnounceLog::announces()) {
        JsonObject o = announces.add<JsonObject>();
        o["dest"]          = rec.destination.toHex();
        o["display_name"]  = rec.display_name;
        o["aspect"]        = rec.aspect;
        o["received_ms"]   = rec.received_ms;
        o["age_ms"]        = millis() - rec.received_ms;
        if (rec.received_ms > announces_high_water) announces_high_water = rec.received_ms;
      }

      JsonArray paths = doc["paths"].to<JsonArray>();
      uint32_t paths_high_water = 0;
      for (const auto& rec : LXMF::AnnounceLog::paths()) {
        JsonObject o = paths.add<JsonObject>();
        o["dest"]          = rec.destination.toHex();
        o["display_name"]  = rec.display_name;
        o["aspect"]        = rec.aspect;
        o["received_ms"]   = rec.received_ms;
        o["age_ms"]        = millis() - rec.received_ms;
        if (rec.received_ms > paths_high_water) paths_high_water = rec.received_ms;
      }

      // Since markers — SPA passes these to /events on first SSE connect.
      JsonObject markers = doc["markers"].to<JsonObject>();
      markers["inbox_since"]     = a->inbox  ? a->inbox->next_seq()  - 1 : 0;
      markers["announces_since"] = announces_high_water;
      markers["paths_since"]     = paths_high_water;

      // Display-time anchor: SPA snapshots (Date.now_browser, now_ms)
      // at fetch time and computes wall-clock for any record via
      //   wall = anchor_browser - (now_ms - received_ms)
      // Only meaningful for records with boot_epoch == current_boot
      // (millis() resets across boots) — for older boots the SPA
      // should fall back to "previously" / no relative time.
      JsonObject clock = doc["clock"].to<JsonObject>();
      clock["now_ms"]            = millis();
      clock["current_boot_epoch"] = Web::BootCounter::current();

      send_json(200, doc);
    }

    static void handle_events() {
      // Short-poll dressed as SSE: drain any events newer than the per-stream
      // since markers, send a retry: hint so the browser reconnects quickly,
      // and return. This keeps the main Arduino task free to service the
      // LoRa modem and reticulum.loop() — parking the handler for any
      // meaningful duration would block both, since handleClient() runs
      // synchronously inside the same loop iteration.
      //
      // Three independent since markers tracked per-stream:
      //   inbox_since      — per-identity monotonic seq (was `since` in v0)
      //   announces_since  — global received_ms threshold (lxmf.delivery only)
      //   paths_since      — global received_ms threshold (every aspect)
      // The browser advances each marker as events arrive.
      LXMF::IdentityId caller = require_auth();
      if (caller.empty()) return;
      std::string requested = std::string(server.pathArg(0).c_str());
      if (caller != requested) { send_error(403, "forbidden"); return; }
      const LXMF::LXMFIdentity* a = LXMF::LXMFGateway::identity_by_id(requested);
      if (!a || !a->inbox) { send_error(404, "unknown_identity"); return; }

      // Accept both the legacy `since` and the new `inbox_since` query name.
      uint32_t inbox_since = (uint32_t)server.arg("inbox_since").toInt();
      if (inbox_since == 0) inbox_since = (uint32_t)server.arg("since").toInt();
      uint32_t announces_since = (uint32_t)server.arg("announces_since").toInt();
      uint32_t paths_since     = (uint32_t)server.arg("paths_since").toInt();

      server.sendHeader("Cache-Control", "no-cache");
      server.sendHeader("Connection", "close");
      server.setContentLength(CONTENT_LENGTH_UNKNOWN);
      server.send(200, "text/event-stream", "");
      // Tell EventSource to reconnect every 500 ms instead of the 3 s
      // browser default. Combined with the immediate return below this
      // gives sub-second event-delivery latency without busy-parking.
      server.sendContent("retry: 500\n\n");

      // 1. Inbox messages since the per-identity seq marker.
      auto pending = a->inbox->since(inbox_since);
      for (const auto& m : pending) {
        JsonDocument item;
        item["type"] = "incoming";
        JsonObject msg = item["msg"].to<JsonObject>();
        msg["seq"]         = m.seq;
        msg["ts"]          = m.ts;
        msg["boot_epoch"]  = m.boot_epoch;
        msg["received_ms"] = m.received_ms;
        msg["peer"]        = m.peer_hash.toHex();
        msg["title"]       = m.title;
        msg["body"]        = m.content;
        msg["sig_ok"]      = m.signature_ok;
        String line;
        serializeJson(item, line);
        server.sendContent(String("data: ") + line + "\n\n");
      }
      // 2. Announces ring (lxmf.delivery only), filtered by received_ms.
      for (const auto& rec : LXMF::AnnounceLog::announces()) {
        if (rec.received_ms <= announces_since) continue;
        JsonDocument item;
        item["type"]          = "announce_seen";
        item["dest"]          = rec.destination.toHex();
        item["display_name"]  = rec.display_name;
        item["aspect"]        = rec.aspect;
        item["received_ms"]   = rec.received_ms;
        item["age_ms"]        = millis() - rec.received_ms;
        String line;
        serializeJson(item, line);
        server.sendContent(String("data: ") + line + "\n\n");
      }
      // 3. Paths ring (every aspect), filtered by received_ms.
      for (const auto& rec : LXMF::AnnounceLog::paths()) {
        if (rec.received_ms <= paths_since) continue;
        JsonDocument item;
        item["type"]          = "path_seen";
        item["dest"]          = rec.destination.toHex();
        item["display_name"]  = rec.display_name;
        item["aspect"]        = rec.aspect;
        item["received_ms"]   = rec.received_ms;
        item["age_ms"]        = millis() - rec.received_ms;
        String line;
        serializeJson(item, line);
        server.sendContent(String("data: ") + line + "\n\n");
      }
      // 4. Identity-code edge events (button-press triggered).
      if (_id_code_event_pending) {
        _id_code_event_pending = false;
        server.sendContent("data: {\"type\":\"identity_code_available\"}\n\n");
      }
      // 5. Resource transfer progress for messages owned by this identity.
      // Filter the ring by identity_id + caller's progress_since marker
      // so each identity's stream only sees its own transfers.
      uint32_t progress_since = (uint32_t)server.arg("progress_since").toInt();
      for (const auto& ev : progress_ring()) {
        if (ev.seq <= progress_since) continue;
        if (ev.identity_id != caller) continue;
        JsonDocument item;
        item["type"]        = ev.finished ? "message_complete" : "message_progress";
        item["seq"]         = ev.seq;
        item["peer"]        = ev.peer_hash.toHex();
        item["link_hash"]   = ev.link_hash.toHex();
        item["incoming"]    = ev.incoming;
        item["bytes_done"]  = ev.bytes_done;
        item["bytes_total"] = ev.bytes_total;
        item["finished"]    = ev.finished;
        String line;
        serializeJson(item, line);
        server.sendContent(String("data: ") + line + "\n\n");
      }
      // Connection closes when the handler returns; browser reconnects
      // after `retry:` ms with the advanced since markers.
    }

    // Verify that this request has physical-presence authority — either a
    // valid bearer token (which required a button press to obtain) or a
    // current identity_code in the request body.
    static bool require_physical_auth(const JsonDocument& body) {
      String h = server.header("Authorization");
      if (h.startsWith("Bearer ")) {
        String hex_str = h.substring(7); hex_str.trim();
        LXMF::IdentityId acc = AuthTokens::validate(std::string(hex_str.c_str()));
        if (!acc.empty()) return true;
      }
      const char* code = body["identity_code"] | "";
      const char* code_err = explain_identity_code_failure(code);
      if (code_err == nullptr) return true;
      send_error_with_message(401, "identity_code_required", code_err);
      return false;
    }

    static void handle_wifi_scan() {
      // Scan results aren't sensitive; gate only the configure write.
      int n = WiFi.scanNetworks();
      JsonDocument doc;
      JsonArray arr = doc["networks"].to<JsonArray>();
      for (int i = 0; i < n; i++) {
        JsonObject obj = arr.add<JsonObject>();
        obj["ssid"]    = WiFi.SSID(i);
        obj["rssi"]    = WiFi.RSSI(i);
        obj["secure"]  = WiFi.encryptionType(i) != WIFI_AUTH_OPEN;
      }
      WiFi.scanDelete();
      send_json(200, doc);
    }

    static void handle_wifi_configure() {
      JsonDocument body;
      if (!read_body_json(body)) return;
      if (!require_physical_auth(body)) return;
      String ssid = body["ssid"] | "";
      String psk  = body["psk"]  | "";
      if (ssid.length() == 0 || ssid.length() > 32) {
        send_error(400, "invalid_ssid");
        return;
      }
      if (psk.length() > 32) {
        send_error(400, "invalid_psk");
        return;
      }
      // Write SSID, PSK, and STA mode to EEPROM using the same code paths
      // as CMD_WIFI_SSID / CMD_WIFI_PSK / CMD_WIFI_MODE in serial_callback.
      for (uint8_t i = 0; i < 33; i++) {
        uint8_t c = (i < ssid.length() && i < 32) ? (uint8_t)ssid[i] : 0x00;
        eeprom_update(config_addr(ADDR_CONF_SSID + i), c);
      }
      for (uint8_t i = 0; i < 33; i++) {
        uint8_t c = (i < psk.length() && i < 32) ? (uint8_t)psk[i] : 0x00;
        eeprom_update(config_addr(ADDR_CONF_PSK + i), c);
      }
      wr_conf_save(WR_WIFI_STA);

      JsonDocument doc;
      doc["status"]  = "saved";
      doc["restart"] = true;
      send_json(200, doc);

      // Reboot so STA mode applies cleanly.
      delay(500);
      ESP.restart();
    }

    static void handle_radio_get() {
      if (require_auth().empty()) return;
      JsonDocument doc;
      doc["frequency"]        = (uint32_t)lora_freq;
      doc["bandwidth"]        = (uint32_t)lora_bw;
      doc["spreading_factor"] = lora_sf;
      doc["coding_rate"]      = lora_cr;
      doc["tx_power"]         = lora_txp;
      // Current airtime caps. Settable via POST /api/radio/airtime; not
      // EEPROM-persisted yet, so they default to the firmware values
      // in Config.h after every boot. Surfaced here so the SPA can show
      // them in the same form the user uses to pick a region preset.
      doc["airtime_limit_pct"]          = (int)(st_airtime_limit * 100);
      doc["longterm_airtime_limit_pct"] = (int)(lt_airtime_limit * 100);
      doc["have_conf"]    = eeprom_have_conf();
      doc["radio_online"] = radio_online;
      doc["op_mode"]      = (op_mode == MODE_TNC) ? "tnc" : "host";
      // Soft limits — actual modem-side validation happens on the next boot.
      doc["limits"]["sf_min"]  = 5;
      doc["limits"]["sf_max"]  = 12;
      doc["limits"]["cr_min"]  = 5;
      doc["limits"]["cr_max"]  = 8;
      doc["limits"]["txp_max"] = 22;
      send_json(200, doc);
    }

    static void handle_radio_set() {
      JsonDocument body;
      if (!read_body_json(body)) return;
      if (!require_physical_auth(body)) return;
      // Accept the long field names the SPA uses. (Earlier versions used
      // short names freq_hz/bw_hz/sf/cr/txp — those are gone.)
      // airtime_limit_pct + longterm_airtime_limit_pct are optional —
      // when present they're persisted to EEPROM alongside the band
      // params and applied in-RAM immediately. Missing fields keep the
      // current (loaded-or-default) values.
      uint32_t freq = (uint32_t)(body["frequency"]        | 0);
      uint32_t bw   = (uint32_t)(body["bandwidth"]        | 0);
      int      sf   = (int)     (body["spreading_factor"] | -1);
      int      cr   = (int)     (body["coding_rate"]      | -1);
      int      txp  = (int)     (body["tx_power"]         | -1);
      // Per-field validation so the error names which field failed.
      char msg[160];
      if (freq < 100000000u || freq > 2500000000u) {
        snprintf(msg, sizeof(msg), "Frequency must be 100 MHz – 2.5 GHz (got %lu Hz). Tip: pick a region preset.", (unsigned long)freq);
        send_error_with_message(400, "invalid_radio_params", msg); return;
      }
      if (bw < 7800 || bw > 500000) {
        snprintf(msg, sizeof(msg), "Bandwidth must be 7.8 kHz – 500 kHz (got %lu Hz). Common: 125000.", (unsigned long)bw);
        send_error_with_message(400, "invalid_radio_params", msg); return;
      }
      if (sf < 5 || sf > 12) {
        snprintf(msg, sizeof(msg), "Spreading factor must be 5–12 (got %d). Common: 7 for speed, 11 for range.", sf);
        send_error_with_message(400, "invalid_radio_params", msg); return;
      }
      if (cr < 5 || cr > 8) {
        snprintf(msg, sizeof(msg), "Coding rate must be 5–8 (4/5 through 4/8). Got %d. Common: 5.", cr);
        send_error_with_message(400, "invalid_radio_params", msg); return;
      }
      if (txp < 0 || txp > 22) {
        snprintf(msg, sizeof(msg), "TX power must be 0–22 dBm (got %d). Regulatory limit varies by region.", txp);
        send_error_with_message(400, "invalid_radio_params", msg); return;
      }
      // Direct EEPROM write, mirroring eeprom_conf_save() but bypassing
      // its hw_ready+radio_online guard. On a fresh device the radio is
      // offline because no saved config exists, which is the very state
      // this endpoint is meant to resolve. Address layout matches
      // ROM.h ADDR_CONF_{SF,CR,TXP,BW,FREQ,OK}.
      eeprom_update(eeprom_addr(ADDR_CONF_SF),  (uint8_t)sf);
      eeprom_update(eeprom_addr(ADDR_CONF_CR),  (uint8_t)cr);
      eeprom_update(eeprom_addr(ADDR_CONF_TXP), (uint8_t)txp);
      eeprom_update(eeprom_addr(ADDR_CONF_BW)+0,  (uint8_t)(bw >> 24));
      eeprom_update(eeprom_addr(ADDR_CONF_BW)+1,  (uint8_t)(bw >> 16));
      eeprom_update(eeprom_addr(ADDR_CONF_BW)+2,  (uint8_t)(bw >> 8));
      eeprom_update(eeprom_addr(ADDR_CONF_BW)+3,  (uint8_t)bw);
      eeprom_update(eeprom_addr(ADDR_CONF_FREQ)+0, (uint8_t)(freq >> 24));
      eeprom_update(eeprom_addr(ADDR_CONF_FREQ)+1, (uint8_t)(freq >> 16));
      eeprom_update(eeprom_addr(ADDR_CONF_FREQ)+2, (uint8_t)(freq >> 8));
      eeprom_update(eeprom_addr(ADDR_CONF_FREQ)+3, (uint8_t)freq);
      // Optional airtime fields — only touch EEPROM when caller sent them
      // (vs no-op). Stored as integer percentage (0..99) and converted to
      // fraction on load. 0xFF sentinel is reserved for "never set".
      if (body["airtime_limit_pct"].is<int>()) {
        const int v = body["airtime_limit_pct"];
        if (v < 0 || v > 99) {
          snprintf(msg, sizeof(msg),
                   "airtime_limit_pct must be 0-99 (got %d). 0 disables the cap.", v);
          send_error_with_message(400, "invalid_radio_params", msg); return;
        }
        eeprom_update(eeprom_addr(ADDR_CONF_AIRTIME), (uint8_t)v);
        st_airtime_limit = (float)v / 100.0f;
      }
      if (body["longterm_airtime_limit_pct"].is<int>()) {
        const int v = body["longterm_airtime_limit_pct"];
        if (v < 0 || v > 99) {
          snprintf(msg, sizeof(msg),
                   "longterm_airtime_limit_pct must be 0-99 (got %d). 0 disables the cap.", v);
          send_error_with_message(400, "invalid_radio_params", msg); return;
        }
        eeprom_update(eeprom_addr(ADDR_CONF_LT_AIRTIME), (uint8_t)v);
        lt_airtime_limit = (float)v / 100.0f;
      }
      eeprom_update(eeprom_addr(ADDR_CONF_OK), CONF_OK_BYTE);

      JsonDocument doc;
      doc["status"]  = "saved";
      doc["restart"] = true;
      send_json(200, doc);
      delay(500);
      ESP.restart();
    }

    static void handle_radio_reset() {
      JsonDocument body;
      if (!read_body_json(body)) return;
      if (!require_physical_auth(body)) return;
      eeprom_update(eeprom_addr(ADDR_CONF_OK), 0x00);
      JsonDocument doc;
      doc["status"]  = "cleared";
      doc["restart"] = true;
      send_json(200, doc);
      delay(500);
      ESP.restart();
    }

    // POST /api/radio/airtime — set short / long airtime duty-cycle caps
    // at runtime. Body: { "airtime_limit_pct": <int>,
    //                     "longterm_airtime_limit_pct": <int>,
    //                     "identity_code": "abc123" (only if no bearer) }
    // Either or both limit fields can be omitted to leave that one alone.
    // Setting a field to 0 disables that limit (which is illegal in
    // regulated bands — caller's responsibility). Values are NOT persisted
    // across reboots yet; the firmware default in Config.h applies on next
    // boot. (See task #57 for EEPROM persistence.)
    static void handle_radio_airtime() {
      JsonDocument body;
      if (!read_body_json(body)) return;
      if (!require_physical_auth(body)) return;

      const bool has_st = body["airtime_limit_pct"].is<int>();
      const bool has_lt = body["longterm_airtime_limit_pct"].is<int>();
      if (!has_st && !has_lt) {
        send_error_with_message(400, "no_fields",
          "Body must include airtime_limit_pct and/or longterm_airtime_limit_pct (integer 0-99).");
        return;
      }
      if (has_st) {
        const int v = body["airtime_limit_pct"];
        if (v < 0 || v > 99) {
          char msg[120];
          snprintf(msg, sizeof(msg),
                   "airtime_limit_pct must be 0-99 (got %d). 0 disables the cap.", v);
          send_error_with_message(400, "invalid_limit", msg); return;
        }
        st_airtime_limit = (v == 0) ? 0.0f : ((float)v / 100.0f);
      }
      if (has_lt) {
        const int v = body["longterm_airtime_limit_pct"];
        if (v < 0 || v > 99) {
          char msg[120];
          snprintf(msg, sizeof(msg),
                   "longterm_airtime_limit_pct must be 0-99 (got %d). 0 disables the cap.", v);
          send_error_with_message(400, "invalid_limit", msg); return;
        }
        lt_airtime_limit = (v == 0) ? 0.0f : ((float)v / 100.0f);
      }
      // Recompute the lock state right away so the response reflects the
      // new configuration. Without this the API would lie about what's
      // active until the next 1-second airtime update tick.
      airtime_lock = false;
      if (st_airtime_limit != 0.0f && airtime          >= st_airtime_limit) airtime_lock = true;
      if (lt_airtime_limit != 0.0f && longterm_airtime >= lt_airtime_limit) airtime_lock = true;

      JsonDocument doc;
      doc["airtime_limit_pct"]          = (int)(st_airtime_limit * 100);
      doc["longterm_airtime_limit_pct"] = (int)(lt_airtime_limit * 100);
      doc["airtime_locked"]             = airtime_lock;
      doc["persisted"]                  = false;   // RAM-only for now
      send_json(200, doc);
      NOTICEF("Airtime caps set via API: st=%d%% lt=%d%% lock=%d",
              (int)(st_airtime_limit*100), (int)(lt_airtime_limit*100), (int)airtime_lock);
    }

    static void handle_paths_list() {
      if (require_auth().empty()) return;
      // We read from AnnounceLog::paths() rather than Transport's path
      // table because microReticulum's get_path_table() returns the
      // in-memory _path_table which is dead code in current versions
      // (see Transport.cpp:2204-2216 — the surrounding logic was
      // migrated to the microStore-backed _new_path_table which has no
      // public iteration API). Our path log is fed by an
      // AnnounceHandler registered with nullptr aspect_filter, so it
      // sees every announce regardless of aspect.
      const auto& ring = LXMF::AnnounceLog::paths();
      JsonDocument doc;
      JsonArray arr = doc["paths"].to<JsonArray>();
      uint32_t now = millis();
      for (auto it = ring.rbegin(); it != ring.rend(); ++it) {
        JsonObject obj = arr.add<JsonObject>();
        obj["dest"]   = it->destination.toHex();
        obj["age_ms"] = (uint32_t)(now - it->received_ms);
        if (!it->display_name.empty()) obj["display_name"] = it->display_name;
        // aspect: lxmf.delivery / lxmf.propagation / nomadnetwork.node /
        // empty (= transport identity or unrecognised application).
        obj["aspect"] = it->aspect.empty() ? "transport" : it->aspect;
        // Live hop count from Transport.
        obj["hops"]   = (int)RNS::Transport::hops_to(it->destination);
      }
      doc["count"] = (uint32_t)ring.size();
      send_json(200, doc);
    }

    static void handle_path_lookup() {
      LXMF::IdentityId caller = require_auth();
      if (caller.empty()) return;
      JsonDocument body;
      if (!read_body_json(body)) return;
      std::string to_hex = (const char*)(body["to"] | "");
      RNS::Bytes to = hex_to_bytes(to_hex, LXMF::HASH_LEN);
      if (to.size() != LXMF::HASH_LEN) {
        send_error(400, "invalid_destination_hash");
        return;
      }
      bool known = RNS::Transport::has_path(to);
      JsonDocument doc;
      doc["known"] = known;
      if (!known) {
        RNS::Transport::request_path(to);
        doc["requested"] = true;
      }
      send_json(200, doc);
    }

  public:
    // ---- Resource transfer progress ring -----------------------------
    // A tiny ring of recent `message_progress` events. Each LXMF Resource
    // send/receive fires a progress callback per part; we publish those
    // to the per-identity SSE stream so the SPA can show a "5 KB / 12 KB"
    // bar on a message bubble that's still mid-flight.
    //
    // Bounded ring (~16 entries) — the SPA polls every 500 ms via SSE
    // reconnect, and we issue ~2-3 progress events per part, so even a
    // 1 MiB resource at SDU≈300 B = ~3000 parts spread over many seconds
    // can't overrun the ring.
    struct ProgressEvent {
      uint32_t           seq;
      LXMF::IdentityId   identity_id;
      RNS::Bytes         peer_hash;
      RNS::Bytes         link_hash;
      bool               incoming;
      uint32_t           bytes_done;
      uint32_t           bytes_total;
      bool               finished;   // true on completion → SPA swaps for final bubble
    };
    static std::deque<ProgressEvent>& progress_ring() {
      static std::deque<ProgressEvent> r;
      return r;
    }
    static uint32_t next_progress_seq() {
      static uint32_t s = 0;
      return ++s;
    }

  private:
    static inline bool     _started = false;
    static inline uint32_t _last_sweep = 0;
    static inline bool     _id_code_event_pending = false;
  };

  // Free function the LXMF gateway calls to publish a Resource-transfer
  // progress event. Implemented here as inline so it's visible everywhere
  // WebUI.h is included; declared as a free function (not a static member)
  // so LXMFGateway.h — which is *included by* WebUI.h — can forward-
  // declare and call it without re-including WebUI.h (which would loop).
  inline void publish_lxmf_progress(const LXMF::IdentityId& identity_id,
                                    const RNS::Bytes& peer_hash,
                                    const RNS::Bytes& link_hash,
                                    bool incoming,
                                    uint32_t bytes_done,
                                    uint32_t bytes_total,
                                    bool finished) {
    auto& r = WebUI::progress_ring();
    r.push_back({WebUI::next_progress_seq(), identity_id, peer_hash, link_hash,
                 incoming, bytes_done, bytes_total, finished});
    while (r.size() > 16) r.pop_front();
  }

}
